module.exports = {
  helper_id: 'checkbox-default-helper',
  helper_text: 'Helper text for the group',
  invalid_text: 'Error message for the group',
  label: 'Select your preferred destinations',
  label_id: 'checkbox-default-label',
  optional_text: '(optional)',
  required_text: '*',
  name: 'checkbox-default',
  invalid_icon: {
    path: '/icons.svg',
    type: 'notifications',
    name: 'warning',
    size: 'm',
  },
  items: [
    {
      checked: true,
      helper_id: 'helper-default-1',
      helper_text: 'Helper text for option 1',
      id: 'checkbox-default-1',
      label: 'Spain',
      value: 'es',
      icon_path: '/icons.svg',
    },
    {
      helper_id: 'helper-default-2',
      id: 'checkbox-default-2',
      label: 'Belgium',
      value: 'be',
      helper_text: 'Helper text for option 2',
      icon_path: '/icons.svg',
    },
    {
      disabled: true,
      helper_id: 'helper-default-3',
      helper_text: 'Helper text for option 3',
      id: 'checkbox-default-3',
      label: 'France (disabled)',
      value: 'fr',
      icon_path: '/icons.svg',
    },
  ],
};
