#!/usr/bin/env node
/**
 * ECL EDS theme: token generator.
 *
 * Reads the raw Figma "W3C Design Tokens" JSON exports committed under
 * `tokens/source/` (Primitives.json, Light.tokens.json, Dark.tokens.json) and
 * generates:
 *   - maps/primitives.scss    ($eds-primitive-* Sass maps, one per top-level
 *                              primitive category)
 *   - maps/color.scss         ($eds-color-light / $eds-color-dark semantic
 *                              color maps, incl. a composite shadow value per
 *                              elevation level)
 *   - maps/spacing.scss       ($eds-spacing, $eds-sizing)
 *   - maps/typography.scss    ($eds-font-family, $eds-font-size, etc.)
 *   - maps/shape.scss         ($eds-border-radius, $eds-border-width)
 *   - maps/opacity.scss       ($eds-opacity)
 *   - _custom-properties.scss (:root + [data-theme="dark"] CSS custom
 *                              properties, generated from the semantic maps)
 *   - tokens/tokens.json       (flat, resolved reference export: every
 *                              primitive + semantic token, its value, type,
 *                              and — for semantic tokens — the primitive it
 *                              aliases)
 *
 * This is codegen: re-run this script after replacing the source JSON files,
 * review the diff, and commit the regenerated output alongside it.
 *
 * Usage: node scripts/generate-tokens.js
 */

const fs = require('fs');
const path = require('path');
const { flatten, cssVarName } = require('./token-names');

const ROOT = path.join(__dirname, '..');
const SOURCE_DIR = path.join(ROOT, 'tokens/source');
const MAPS_DIR = path.join(ROOT, 'maps');

const GENERATED_BANNER = `// This file is generated by \`scripts/generate-tokens.js\` from the JSON
// files in \`tokens/source/\`. Do not edit by hand — re-run the script and
// commit the diff instead.\n`;

// -----------------------------------------------------------------------
// Value conversion
// -----------------------------------------------------------------------

function pxToRem(px) {
  const rem = px / 16;
  // Trim floating point noise (e.g. 0.1 + 0.2), keep up to 4 decimals.
  return `${parseFloat(rem.toFixed(4))}rem`;
}

function percentStringToEm(value) {
  // Figma exports letter-spacing / paragraph-spacing as a percentage of the
  // font size ("2%", "150%", "0"). That is exactly what CSS `em` means
  // relative to the current font-size, so "2%" -> "0.02em".
  if (typeof value !== 'string') return value;
  const match = value.trim().match(/^(-?\d+(?:\.\d+)?)%$/);
  if (!match) return value === '0' ? '0' : value;
  const fraction = parseFloat(match[1]) / 100;
  return fraction === 0 ? '0' : `${parseFloat(fraction.toFixed(4))}em`;
}

// Shortens a #RRGGBB[AA] hex string to #RGB[A] when every channel pair
// repeats its digit (stylelint's color-hex-length rule requires this).
function shortenHex(hex) {
  const pairs = hex.slice(1).match(/.{2}/g);
  const canShorten = pairs.every((pair) => pair[0] === pair[1]);
  if (!canShorten) return hex;
  return `#${pairs.map((pair) => pair[0]).join('')}`;
}

function colorToHex(value) {
  const alphaHex =
    value.alpha === 1
      ? ''
      : Math.round(value.alpha * 255)
          .toString(16)
          .padStart(2, '0')
          .toUpperCase();
  return shortenHex(`${value.hex}${alphaHex}`);
}

/** Renders a token's $value as a Sass literal, per its $type / path. */
function toScssValue(pathSegments, type, value) {
  const category = pathSegments[0];

  if (type === 'color') return colorToHex(value);

  if (type === 'string') {
    if (
      category === 'font' &&
      (pathSegments[1] === 'letter-spacing' ||
        pathSegments[1] === 'paragraph-spacing')
    ) {
      return percentStringToEm(value);
    }
    // text-decoration values ("none", "Underline", "Uppercase") are CSS
    // keywords - lowercase them and pass through unquoted.
    if (category === 'font' && pathSegments[1] === 'text-decoration') {
      return value.toLowerCase();
    }
    // The source only names the typeface itself ("Inter") with no fallback
    // stack, so a browser that hasn't loaded it falls back to whatever
    // default the UA picks (often a serif) instead of a plain sans-serif.
    // Append a generic fallback, matching ec's own $font-family convention.
    if (category === 'font' && pathSegments[1] === 'family') {
      return `'${value}', arial, sans-serif`;
    }
    return `'${value}'`;
  }

  if (type === 'number') {
    if (category === 'opacity') return `${value / 100}`;
    if (category === 'border-radius' || category === 'border-width') {
      return `${value}px`;
    }
    if (category === 'shadow') return `${value}px`; // offset/blur/spread
    if (category === 'font' && pathSegments[1] === 'paragraph-spacing') {
      return `${value}`; // 0 (the '150%' case is a string, handled above)
    }
    if (category === 'font' && pathSegments[1] === 'weight') return `${value}`;
    // dimension, sizing, spacing, font/size, font/line-height -> rem
    return pxToRem(value);
  }

  throw new Error(
    `Unhandled token type "${type}" at ${pathSegments.join('/')}`,
  );
}

// -----------------------------------------------------------------------
// Sass map rendering
// -----------------------------------------------------------------------

/** Renders a nested object as a Sass map literal (2-space indent per level). */
function renderScssMap(node, indent = 0) {
  const pad = '  '.repeat(indent);
  const innerPad = '  '.repeat(indent + 1);
  const isLeaf = typeof node !== 'object';
  if (isLeaf) {
    // A leaf value with a top-level comma (e.g. a 'Inter', arial,
    // sans-serif font stack) would otherwise be misread as multiple map
    // entries by the Sass parser - wrap it as a single list value instead.
    if (typeof node === 'string' && node.includes(',')) return `(${node})`;
    return node;
  }

  const entries = Object.keys(node).map((key) => {
    const quotedKey = `'${key}'`;
    return `${innerPad}${quotedKey}: ${renderScssMap(node[key], indent + 1)}`;
  });
  return `(\n${entries.join(',\n')},\n${pad})`;
}

// -----------------------------------------------------------------------
// Load sources
// -----------------------------------------------------------------------

const primitivesRaw = JSON.parse(
  fs.readFileSync(path.join(SOURCE_DIR, 'Primitives.json'), 'utf8'),
);
const lightRaw = JSON.parse(
  fs.readFileSync(path.join(SOURCE_DIR, 'Light.tokens.json'), 'utf8'),
);
const darkRaw = JSON.parse(
  fs.readFileSync(path.join(SOURCE_DIR, 'Dark.tokens.json'), 'utf8'),
);

const primitives = flatten(primitivesRaw);
delete primitives.system; // Figma-only documentation swatch, not a design token
Object.keys(primitives).forEach((key) => {
  if (key.startsWith('system/')) delete primitives[key];
});

const light = flatten(lightRaw);
const dark = flatten(darkRaw);

// -----------------------------------------------------------------------
// 1. Primitives Sass map
// -----------------------------------------------------------------------

function buildPrimitivesScss() {
  const byCategory = {};
  Object.keys(primitives).forEach((key) => {
    const segments = key.split('/');
    const category = segments[0];
    const rest = segments.slice(1);
    const node = primitives[key];
    const scssValue = toScssValue(segments, node.$type, node.$value);
    byCategory[category] = byCategory[category] || {};
    let cursor = byCategory[category];
    rest.forEach((segment, i) => {
      if (i === rest.length - 1) {
        cursor[segment] = scssValue;
      } else {
        cursor[segment] = cursor[segment] || {};
        cursor = cursor[segment];
      }
    });
  });

  let out = GENERATED_BANNER;
  out += '\n// Raw design tokens ("Primitives" in Figma) — the atomic values\n';
  out += '// semantic light/dark tokens alias into. Not mode-dependent.\n\n';
  out += Object.keys(byCategory)
    .sort()
    .map(
      (category) =>
        `$eds-primitive-${category}: ${renderScssMap(byCategory[category])} !default;`,
    )
    .join('\n');
  out += '\n';
  return out;
}

// -----------------------------------------------------------------------
// 2. Semantic maps, split: color (mode-scoped) vs everything else (invariant)
// -----------------------------------------------------------------------

function splitSemantic(flatDict) {
  const color = {};
  const rest = {};
  Object.keys(flatDict).forEach((key) => {
    const node = flatDict[key];
    if (node.$type === 'color') {
      color[key] = node;
    } else {
      rest[key] = node;
    }
  });
  return { color, rest };
}

const lightSplit = splitSemantic(light);
const darkSplit = splitSemantic(dark);

function buildColorScssMap(colorDict) {
  const nested = {};
  Object.keys(colorDict).forEach((key) => {
    const segments = key.split('/');
    const node = colorDict[key];
    const scssValue = toScssValue(segments, node.$type, node.$value);
    let cursor = nested;
    segments.forEach((segment, i) => {
      if (i === segments.length - 1) {
        cursor[segment] = scssValue;
      } else {
        cursor[segment] = cursor[segment] || {};
        cursor = cursor[segment];
      }
    });
  });
  return nested;
}

// Composite `box-shadow`-ready value per elevation level, built from the
// (mode-scoped) shadow color + the (mode-invariant) offset/blur/spread.
function buildShadowComposites(colorDict, restDict) {
  const levels = new Set();
  Object.keys(colorDict).forEach((key) => {
    const match = key.match(/^shadow\/elevation\/(level-\d+)\/color$/);
    if (match) levels.add(match[1]);
  });
  const composites = {};
  levels.forEach((level) => {
    const x = toScssValue(
      ['shadow'],
      'number',
      restDict[`shadow/elevation/${level}/x`].$value,
    );
    const y = toScssValue(
      ['shadow'],
      'number',
      restDict[`shadow/elevation/${level}/y`].$value,
    );
    const blur = toScssValue(
      ['shadow'],
      'number',
      restDict[`shadow/elevation/${level}/blur`].$value,
    );
    const spread = toScssValue(
      ['shadow'],
      'number',
      restDict[`shadow/elevation/${level}/spread`].$value,
    );
    const color = toScssValue(
      ['shadow'],
      'color',
      colorDict[`shadow/elevation/${level}/color`].$value,
    );
    composites[level] = `${x} ${y} ${blur} ${spread} ${color}`;
  });
  return composites;
}

function buildColorMapsScss() {
  const lightNested = buildColorScssMap(lightSplit.color);
  const darkNested = buildColorScssMap(darkSplit.color);
  const lightShadowComposite = buildShadowComposites(
    lightSplit.color,
    lightSplit.rest,
  );
  const darkShadowComposite = buildShadowComposites(
    darkSplit.color,
    darkSplit.rest,
  );
  lightNested.shadow = lightNested.shadow || {};
  lightNested.shadow.composite = lightShadowComposite;
  darkNested.shadow = darkNested.shadow || {};
  darkNested.shadow.composite = darkShadowComposite;

  let out = GENERATED_BANNER;
  out +=
    '\n// Semantic color tokens (mode-dependent). shadow.composite.level-N\n';
  out += '// is a ready-to-use `box-shadow` value combining the mode-scoped\n';
  out += '// shadow color with the mode-invariant offset/blur/spread.\n\n';
  out += `$eds-color-light: ${renderScssMap(lightNested)} !default;\n`;
  out += `$eds-color-dark: ${renderScssMap(darkNested)} !default;\n`;
  return out;
}

function buildInvariantScss(prefix, restDict, categories, banner) {
  const nested = {};
  Object.keys(restDict).forEach((key) => {
    const segments = key.split('/');
    if (!categories.includes(segments[0])) return;
    const node = restDict[key];
    const scssValue = toScssValue(segments, node.$type, node.$value);
    let cursor = nested;
    segments.forEach((segment, i) => {
      if (i === segments.length - 1) {
        cursor[segment] = scssValue;
      } else {
        cursor[segment] = cursor[segment] || {};
        cursor = cursor[segment];
      }
    });
  });

  let out = GENERATED_BANNER;
  out += `\n${banner}\n\n`;
  out += categories
    .filter((category) => nested[category])
    .map(
      (category) =>
        `$eds-${category}: ${renderScssMap(nested[category])} !default;`,
    )
    .join('\n');
  out += '\n';
  return out;
}

// -----------------------------------------------------------------------
// 3. _custom-properties.scss
// -----------------------------------------------------------------------

function buildCustomPropertyLines() {
  const restLines = [];
  const seenRestKeys = new Set();
  Object.keys(lightSplit.rest)
    .sort()
    .forEach((key) => {
      if (seenRestKeys.has(key)) return;
      seenRestKeys.add(key);
      const segments = key.split('/');
      const node = lightSplit.rest[key];
      const scssValue = toScssValue(segments, node.$type, node.$value);
      restLines.push(`  ${cssVarName('eds', segments)}: ${scssValue};`);
    });

  function colorLines(colorDict, restDict) {
    const lines = [];
    Object.keys(colorDict)
      .sort()
      .forEach((key) => {
        const segments = key.split('/');
        const node = colorDict[key];
        const scssValue = toScssValue(segments, node.$type, node.$value);
        lines.push(`  ${cssVarName('eds', segments)}: ${scssValue};`);
      });
    const composites = buildShadowComposites(colorDict, restDict);
    Object.keys(composites)
      .sort()
      .forEach((level) => {
        lines.push(
          `  ${cssVarName('eds', ['shadow', 'elevation', level])}: ${composites[level]};`,
        );
      });
    return lines;
  }

  return {
    restLines,
    lightColorLines: colorLines(lightSplit.color, lightSplit.rest),
    darkColorLines: colorLines(darkSplit.color, darkSplit.rest),
  };
}

function buildCustomPropertiesScss() {
  const { restLines, lightColorLines, darkColorLines } =
    buildCustomPropertyLines();

  let out = GENERATED_BANNER;
  out += '\n:root {\n';
  out += '  // Mode-invariant tokens (spacing, sizing, font, border-radius,\n';
  out += '  // border-width, opacity, shadow offset/blur/spread)\n';
  out += `${restLines.join('\n')}\n\n`;
  out += '  // Semantic color tokens — light mode (default)\n';
  out += `${lightColorLines.join('\n')}\n`;
  out += '}\n\n';
  out += '[data-theme="dark"] {\n';
  out += '  // Semantic color tokens — dark mode\n';
  out += `${darkColorLines.join('\n')}\n`;
  out += '}\n';
  return out;
}

// -----------------------------------------------------------------------
// 4. tokens/tokens.json (flat reference export)
// -----------------------------------------------------------------------

function buildTokensJson() {
  const out = { primitives: {}, light: {}, dark: {} };
  Object.keys(primitives).forEach((key) => {
    const node = primitives[key];
    out.primitives[key] = { type: node.$type, value: node.$value };
  });
  [
    ['light', light],
    ['dark', dark],
  ].forEach(([modeName, dict]) => {
    Object.keys(dict).forEach((key) => {
      const node = dict[key];
      const alias = node.$extensions && node.$extensions['com.figma.aliasData'];
      out[modeName][key] = {
        type: node.$type,
        value: node.$value,
        ...(alias ? { aliasOf: alias.targetVariableName } : {}),
      };
    });
  });
  return out;
}

// -----------------------------------------------------------------------
// Write output
// -----------------------------------------------------------------------

async function main() {
  fs.mkdirSync(MAPS_DIR, { recursive: true });

  fs.writeFileSync(
    path.join(MAPS_DIR, 'primitives.scss'),
    buildPrimitivesScss(),
  );
  fs.writeFileSync(path.join(MAPS_DIR, 'color.scss'), buildColorMapsScss());
  fs.writeFileSync(
    path.join(MAPS_DIR, 'spacing.scss'),
    buildInvariantScss(
      'eds',
      lightSplit.rest,
      ['spacing', 'sizing'],
      '// Mode-invariant spacing / sizing scale.',
    ),
  );
  fs.writeFileSync(
    path.join(MAPS_DIR, 'typography.scss'),
    buildInvariantScss(
      'eds',
      lightSplit.rest,
      ['font'],
      '// Mode-invariant typography scale.',
    ),
  );
  fs.writeFileSync(
    path.join(MAPS_DIR, 'shape.scss'),
    buildInvariantScss(
      'eds',
      lightSplit.rest,
      ['border-radius', 'border-width'],
      '// Mode-invariant border-radius / border-width scale.',
    ),
  );
  fs.writeFileSync(
    path.join(MAPS_DIR, 'opacity.scss'),
    buildInvariantScss(
      'eds',
      lightSplit.rest,
      ['opacity'],
      '// Mode-invariant opacity scale.',
    ),
  );
  fs.writeFileSync(
    path.join(ROOT, '_custom-properties.scss'),
    buildCustomPropertiesScss(),
  );
  fs.writeFileSync(
    path.join(ROOT, 'tokens/tokens.json'),
    `${JSON.stringify(buildTokensJson(), null, 2)}\n`,
  );

  // Re-format everything this script just wrote with the repo's Prettier
  // config, so generated output always matches `pnpm pretty-check`.
  const generatedFiles = [
    path.join(MAPS_DIR, 'primitives.scss'),
    path.join(MAPS_DIR, 'color.scss'),
    path.join(MAPS_DIR, 'spacing.scss'),
    path.join(MAPS_DIR, 'typography.scss'),
    path.join(MAPS_DIR, 'shape.scss'),
    path.join(MAPS_DIR, 'opacity.scss'),
    path.join(ROOT, '_custom-properties.scss'),
    path.join(ROOT, 'tokens/tokens.json'),
  ];
  const prettier = require(
    require.resolve('prettier', { paths: [ROOT, path.join(ROOT, '../../..')] }),
  );
  await Promise.all(
    generatedFiles.map(async (file) => {
      const source = fs.readFileSync(file, 'utf8');
      const config = (await prettier.resolveConfig(file)) || {};
      const formatted = await prettier.format(source, {
        ...config,
        filepath: file,
      });
      fs.writeFileSync(file, formatted);
    }),
  );
  console.log('Generated eds theme tokens:');

  console.log(`  - ${Object.keys(primitives).length} primitives`);

  console.log(
    `  - ${Object.keys(light).length} semantic tokens per mode (light/dark)`,
  );
}

main();
