#!/usr/bin/env node
/**
 * ECL EDS theme: token generator.
 *
 * Reads the raw Figma "W3C Design Tokens" JSON exports committed under
 * `tokens/source/` (Primitives.json, Light.tokens.json, Dark.tokens.json) and
 * generates:
 *   - maps/primitives.scss    ($eds-primitive-* Sass maps, one per top-level
 *                              primitive category)
 *   - maps/color.scss         ($eds-color-light / $eds-color-dark semantic
 *                              color maps, incl. a composite shadow value per
 *                              elevation level)
 *   - maps/spacing.scss       ($eds-spacing, $eds-sizing)
 *   - maps/typography.scss    ($eds-font-family, $eds-font-size, etc.)
 *   - maps/shape.scss         ($eds-border-radius, $eds-border-width)
 *   - maps/opacity.scss       ($eds-opacity)
 *   - _custom-properties.scss (:root + [data-theme="dark"] CSS custom
 *                              properties, generated from the semantic maps)
 *   - tokens/tokens.json       (flat, resolved reference export: every
 *                              primitive + semantic token, its value, type,
 *                              and — for semantic tokens — the primitive it
 *                              aliases)
 *
 * This is codegen: re-run this script after replacing the source JSON files,
 * review the diff, and commit the regenerated output alongside it.
 *
 * Usage: node scripts/generate-tokens.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SOURCE_DIR = path.join(ROOT, 'tokens/source');
const MAPS_DIR = path.join(ROOT, 'maps');
const SHOWCASE_DIR = path.join(ROOT, 'showcase');

const GENERATED_BANNER = `// This file is generated by \`scripts/generate-tokens.js\` from the JSON
// files in \`tokens/source/\`. Do not edit by hand — re-run the script and
// commit the diff instead.\n`;

// -----------------------------------------------------------------------
// JSON flattening
// -----------------------------------------------------------------------

/**
 * Walks a W3C Design Tokens tree and returns a flat map of
 * 'path/joined/with/slashes' -> the token node ({ $type, $value, $extensions }).
 */
function flatten(node, prefix = '', out = {}) {
  if (node && typeof node === 'object') {
    if (Object.prototype.hasOwnProperty.call(node, '$value')) {
      out[prefix] = node;
      return out;
    }
    Object.keys(node).forEach((key) => {
      if (key.startsWith('$')) return;
      flatten(node[key], prefix ? `${prefix}/${key}` : key, out);
    });
  }
  return out;
}

// -----------------------------------------------------------------------
// Value conversion
// -----------------------------------------------------------------------

function pxToRem(px) {
  const rem = px / 16;
  // Trim floating point noise (e.g. 0.1 + 0.2), keep up to 4 decimals.
  return `${parseFloat(rem.toFixed(4))}rem`;
}

function percentStringToEm(value) {
  // Figma exports letter-spacing / paragraph-spacing as a percentage of the
  // font size ("2%", "150%", "0"). That is exactly what CSS `em` means
  // relative to the current font-size, so "2%" -> "0.02em".
  if (typeof value !== 'string') return value;
  const match = value.trim().match(/^(-?\d+(?:\.\d+)?)%$/);
  if (!match) return value === '0' ? '0' : value;
  const fraction = parseFloat(match[1]) / 100;
  return fraction === 0 ? '0' : `${parseFloat(fraction.toFixed(4))}em`;
}

// Shortens a #RRGGBB[AA] hex string to #RGB[A] when every channel pair
// repeats its digit (stylelint's color-hex-length rule requires this).
function shortenHex(hex) {
  const pairs = hex.slice(1).match(/.{2}/g);
  const canShorten = pairs.every((pair) => pair[0] === pair[1]);
  if (!canShorten) return hex;
  return `#${pairs.map((pair) => pair[0]).join('')}`;
}

function colorToHex(value) {
  const alphaHex =
    value.alpha === 1
      ? ''
      : Math.round(value.alpha * 255)
          .toString(16)
          .padStart(2, '0')
          .toUpperCase();
  return shortenHex(`${value.hex}${alphaHex}`);
}

/** Renders a token's $value as a Sass literal, per its $type / path. */
function toScssValue(pathSegments, type, value) {
  const category = pathSegments[0];

  if (type === 'color') return colorToHex(value);

  if (type === 'string') {
    if (
      category === 'font' &&
      (pathSegments[1] === 'letter-spacing' ||
        pathSegments[1] === 'paragraph-spacing')
    ) {
      return percentStringToEm(value);
    }
    // text-decoration values ("none", "Underline", "Uppercase") are CSS
    // keywords - lowercase them and pass through unquoted.
    if (category === 'font' && pathSegments[1] === 'text-decoration') {
      return value.toLowerCase();
    }
    // The source only names the typeface itself ("Inter") with no fallback
    // stack, so a browser that hasn't loaded it falls back to whatever
    // default the UA picks (often a serif) instead of a plain sans-serif.
    // Append a generic fallback, matching ec's own $font-family convention.
    if (category === 'font' && pathSegments[1] === 'family') {
      return `'${value}', arial, sans-serif`;
    }
    return `'${value}'`;
  }

  if (type === 'number') {
    if (category === 'opacity') return `${value / 100}`;
    if (category === 'border-radius' || category === 'border-width') {
      return `${value}px`;
    }
    if (category === 'shadow') return `${value}px`; // offset/blur/spread
    if (category === 'font' && pathSegments[1] === 'paragraph-spacing') {
      return `${value}`; // 0 (the '150%' case is a string, handled above)
    }
    if (category === 'font' && pathSegments[1] === 'weight') return `${value}`;
    // dimension, sizing, spacing, font/size, font/line-height -> rem
    return pxToRem(value);
  }

  throw new Error(
    `Unhandled token type "${type}" at ${pathSegments.join('/')}`,
  );
}

// -----------------------------------------------------------------------
// Sass map rendering
// -----------------------------------------------------------------------

/** Renders a nested object as a Sass map literal (2-space indent per level). */
function renderScssMap(node, indent = 0) {
  const pad = '  '.repeat(indent);
  const innerPad = '  '.repeat(indent + 1);
  const isLeaf = typeof node !== 'object';
  if (isLeaf) {
    // A leaf value with a top-level comma (e.g. a 'Inter', arial,
    // sans-serif font stack) would otherwise be misread as multiple map
    // entries by the Sass parser - wrap it as a single list value instead.
    if (typeof node === 'string' && node.includes(',')) return `(${node})`;
    return node;
  }

  const entries = Object.keys(node).map((key) => {
    const quotedKey = `'${key}'`;
    return `${innerPad}${quotedKey}: ${renderScssMap(node[key], indent + 1)}`;
  });
  return `(\n${entries.join(',\n')},\n${pad})`;
}

// 1-2 char abbreviations for the top-level token category, applied only to
// generated CSS custom property names (kept full-length in Sass map
// variable names) - shrinks the compiled CSS meaningfully given how many
// custom properties this theme emits. Mirrors ec's own shorthand aliases
// (--c-p, --fs-m, --s-m, --sh-1, ...).
const CATEGORY_ABBREVIATIONS = {
  color: 'c',
  spacing: 'sp',
  sizing: 'sz',
  font: 'f',
  'border-radius': 'br',
  'border-width': 'bw',
  opacity: 'op',
  shadow: 'sh',
};

function cssVarName(prefix, pathSegments) {
  const [category, ...rest] = pathSegments;
  const abbreviatedCategory = CATEGORY_ABBREVIATIONS[category] || category;
  const abbreviatedSegments = [abbreviatedCategory, ...rest];
  // Source segments like 'default--hover' use a double dash as an internal
  // state separator; collapse to single dashes so the result is valid
  // kebab-case (stylelint's custom-property-pattern rejects '--' mid-name).
  return `--${prefix}-${abbreviatedSegments.join('-')}`.replace(
    /-{2,}/g,
    (m, offset) => (offset === 0 ? m : '-'),
  );
}

// -----------------------------------------------------------------------
// Load sources
// -----------------------------------------------------------------------

const primitivesRaw = JSON.parse(
  fs.readFileSync(path.join(SOURCE_DIR, 'Primitives.json'), 'utf8'),
);
const lightRaw = JSON.parse(
  fs.readFileSync(path.join(SOURCE_DIR, 'Light.tokens.json'), 'utf8'),
);
const darkRaw = JSON.parse(
  fs.readFileSync(path.join(SOURCE_DIR, 'Dark.tokens.json'), 'utf8'),
);

const primitives = flatten(primitivesRaw);
delete primitives.system; // Figma-only documentation swatch, not a design token
Object.keys(primitives).forEach((key) => {
  if (key.startsWith('system/')) delete primitives[key];
});

const light = flatten(lightRaw);
const dark = flatten(darkRaw);

// -----------------------------------------------------------------------
// 1. Primitives Sass map
// -----------------------------------------------------------------------

function buildPrimitivesScss() {
  const byCategory = {};
  Object.keys(primitives).forEach((key) => {
    const segments = key.split('/');
    const category = segments[0];
    const rest = segments.slice(1);
    const node = primitives[key];
    const scssValue = toScssValue(segments, node.$type, node.$value);
    byCategory[category] = byCategory[category] || {};
    let cursor = byCategory[category];
    rest.forEach((segment, i) => {
      if (i === rest.length - 1) {
        cursor[segment] = scssValue;
      } else {
        cursor[segment] = cursor[segment] || {};
        cursor = cursor[segment];
      }
    });
  });

  let out = GENERATED_BANNER;
  out += '\n// Raw design tokens ("Primitives" in Figma) — the atomic values\n';
  out += '// semantic light/dark tokens alias into. Not mode-dependent.\n\n';
  out += Object.keys(byCategory)
    .sort()
    .map(
      (category) =>
        `$eds-primitive-${category}: ${renderScssMap(byCategory[category])} !default;`,
    )
    .join('\n');
  out += '\n';
  return out;
}

// -----------------------------------------------------------------------
// 2. Semantic maps, split: color (mode-scoped) vs everything else (invariant)
// -----------------------------------------------------------------------

function splitSemantic(flatDict) {
  const color = {};
  const rest = {};
  Object.keys(flatDict).forEach((key) => {
    const node = flatDict[key];
    if (node.$type === 'color') {
      color[key] = node;
    } else {
      rest[key] = node;
    }
  });
  return { color, rest };
}

const lightSplit = splitSemantic(light);
const darkSplit = splitSemantic(dark);

function buildColorScssMap(colorDict) {
  const nested = {};
  Object.keys(colorDict).forEach((key) => {
    const segments = key.split('/');
    const node = colorDict[key];
    const scssValue = toScssValue(segments, node.$type, node.$value);
    let cursor = nested;
    segments.forEach((segment, i) => {
      if (i === segments.length - 1) {
        cursor[segment] = scssValue;
      } else {
        cursor[segment] = cursor[segment] || {};
        cursor = cursor[segment];
      }
    });
  });
  return nested;
}

// Composite `box-shadow`-ready value per elevation level, built from the
// (mode-scoped) shadow color + the (mode-invariant) offset/blur/spread.
function buildShadowComposites(colorDict, restDict) {
  const levels = new Set();
  Object.keys(colorDict).forEach((key) => {
    const match = key.match(/^shadow\/elevation\/(level-\d+)\/color$/);
    if (match) levels.add(match[1]);
  });
  const composites = {};
  levels.forEach((level) => {
    const x = toScssValue(
      ['shadow'],
      'number',
      restDict[`shadow/elevation/${level}/x`].$value,
    );
    const y = toScssValue(
      ['shadow'],
      'number',
      restDict[`shadow/elevation/${level}/y`].$value,
    );
    const blur = toScssValue(
      ['shadow'],
      'number',
      restDict[`shadow/elevation/${level}/blur`].$value,
    );
    const spread = toScssValue(
      ['shadow'],
      'number',
      restDict[`shadow/elevation/${level}/spread`].$value,
    );
    const color = toScssValue(
      ['shadow'],
      'color',
      colorDict[`shadow/elevation/${level}/color`].$value,
    );
    composites[level] = `${x} ${y} ${blur} ${spread} ${color}`;
  });
  return composites;
}

function buildColorMapsScss() {
  const lightNested = buildColorScssMap(lightSplit.color);
  const darkNested = buildColorScssMap(darkSplit.color);
  const lightShadowComposite = buildShadowComposites(
    lightSplit.color,
    lightSplit.rest,
  );
  const darkShadowComposite = buildShadowComposites(
    darkSplit.color,
    darkSplit.rest,
  );
  lightNested.shadow = lightNested.shadow || {};
  lightNested.shadow.composite = lightShadowComposite;
  darkNested.shadow = darkNested.shadow || {};
  darkNested.shadow.composite = darkShadowComposite;

  let out = GENERATED_BANNER;
  out +=
    '\n// Semantic color tokens (mode-dependent). shadow.composite.level-N\n';
  out += '// is a ready-to-use `box-shadow` value combining the mode-scoped\n';
  out += '// shadow color with the mode-invariant offset/blur/spread.\n\n';
  out += `$eds-color-light: ${renderScssMap(lightNested)} !default;\n`;
  out += `$eds-color-dark: ${renderScssMap(darkNested)} !default;\n`;
  return out;
}

function buildInvariantScss(prefix, restDict, categories, banner) {
  const nested = {};
  Object.keys(restDict).forEach((key) => {
    const segments = key.split('/');
    if (!categories.includes(segments[0])) return;
    const node = restDict[key];
    const scssValue = toScssValue(segments, node.$type, node.$value);
    let cursor = nested;
    segments.forEach((segment, i) => {
      if (i === segments.length - 1) {
        cursor[segment] = scssValue;
      } else {
        cursor[segment] = cursor[segment] || {};
        cursor = cursor[segment];
      }
    });
  });

  let out = GENERATED_BANNER;
  out += `\n${banner}\n\n`;
  out += categories
    .filter((category) => nested[category])
    .map(
      (category) =>
        `$eds-${category}: ${renderScssMap(nested[category])} !default;`,
    )
    .join('\n');
  out += '\n';
  return out;
}

// -----------------------------------------------------------------------
// 3. _custom-properties.scss
// -----------------------------------------------------------------------

function buildCustomPropertyLines() {
  const restLines = [];
  const seenRestKeys = new Set();
  Object.keys(lightSplit.rest)
    .sort()
    .forEach((key) => {
      if (seenRestKeys.has(key)) return;
      seenRestKeys.add(key);
      const segments = key.split('/');
      const node = lightSplit.rest[key];
      const scssValue = toScssValue(segments, node.$type, node.$value);
      restLines.push(`  ${cssVarName('eds', segments)}: ${scssValue};`);
    });

  function colorLines(colorDict, restDict) {
    const lines = [];
    Object.keys(colorDict)
      .sort()
      .forEach((key) => {
        const segments = key.split('/');
        const node = colorDict[key];
        const scssValue = toScssValue(segments, node.$type, node.$value);
        lines.push(`  ${cssVarName('eds', segments)}: ${scssValue};`);
      });
    const composites = buildShadowComposites(colorDict, restDict);
    Object.keys(composites)
      .sort()
      .forEach((level) => {
        lines.push(
          `  ${cssVarName('eds', ['shadow', 'elevation', level])}: ${composites[level]};`,
        );
      });
    return lines;
  }

  return {
    restLines,
    lightColorLines: colorLines(lightSplit.color, lightSplit.rest),
    darkColorLines: colorLines(darkSplit.color, darkSplit.rest),
  };
}

function buildCustomPropertiesScss() {
  const { restLines, lightColorLines, darkColorLines } =
    buildCustomPropertyLines();

  let out = GENERATED_BANNER;
  out += '\n:root {\n';
  out += '  // Mode-invariant tokens (spacing, sizing, font, border-radius,\n';
  out += '  // border-width, opacity, shadow offset/blur/spread)\n';
  out += `${restLines.join('\n')}\n\n`;
  out += '  // Semantic color tokens — light mode (default)\n';
  out += `${lightColorLines.join('\n')}\n`;
  out += '}\n\n';
  out += '[data-theme="dark"] {\n';
  out += '  // Semantic color tokens — dark mode\n';
  out += `${darkColorLines.join('\n')}\n`;
  out += '}\n';
  return out;
}

// Same custom properties, but as plain, dependency-free CSS (`/* */`
// comments instead of Sass' `//`) for the standalone showcase page to
// <link> directly — no Sass build step needed to view it.
function buildTokensCss() {
  const { restLines, lightColorLines, darkColorLines } =
    buildCustomPropertyLines();

  let out =
    '/* Generated by `scripts/generate-tokens.js`. Do not edit by hand. */\n';
  out += '\n:root {\n';
  out += `${restLines.join('\n')}\n`;
  out += `${lightColorLines.join('\n')}\n`;
  out += '}\n\n';
  out += '[data-theme="dark"] {\n';
  out += `${darkColorLines.join('\n')}\n`;
  out += '}\n';
  return out;
}

// -----------------------------------------------------------------------
// 4. tokens/tokens.json (flat reference export)
// -----------------------------------------------------------------------

function buildTokensJson() {
  const out = { primitives: {}, light: {}, dark: {} };
  Object.keys(primitives).forEach((key) => {
    const node = primitives[key];
    out.primitives[key] = { type: node.$type, value: node.$value };
  });
  [
    ['light', light],
    ['dark', dark],
  ].forEach(([modeName, dict]) => {
    Object.keys(dict).forEach((key) => {
      const node = dict[key];
      const alias = node.$extensions && node.$extensions['com.figma.aliasData'];
      out[modeName][key] = {
        type: node.$type,
        value: node.$value,
        ...(alias ? { aliasOf: alias.targetVariableName } : {}),
      };
    });
  });
  return out;
}

// -----------------------------------------------------------------------
// 5. showcase/index.html (standalone, dependency-free token browser)
// -----------------------------------------------------------------------

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// Groups a flat { 'color/surface/primary/default': node } dict by its
// second path segment ('surface', 'on-surface', 'border', ...), preserving
// source order within each group.
function groupColorTokens(colorDict) {
  const groups = {};
  Object.keys(colorDict)
    .filter((key) => key.startsWith('color/'))
    .forEach((key) => {
      const segments = key.split('/');
      const groupName = segments[1];
      groups[groupName] = groups[groupName] || [];
      groups[groupName].push(segments);
    });
  return groups;
}

function buildColorSections() {
  const groups = groupColorTokens(lightSplit.color);
  return Object.keys(groups)
    .sort()
    .map((groupName) => {
      const swatches = groups[groupName]
        .map((segments) => {
          const varName = cssVarName('eds', segments);
          const label = segments.slice(2).join(' / ') || segments[1];
          return `        <div class="swatch">
          <div class="swatch-color" style="background: var(${varName})"></div>
          <div class="swatch-label">${escapeHtml(label)}</div>
          <code class="swatch-var">${varName}</code>
        </div>`;
        })
        .join('\n');
      return `      <div class="group">
        <h3>${escapeHtml(groupName)}</h3>
        <div class="swatch-grid">
${swatches}
        </div>
      </div>`;
    })
    .join('\n');
}

function restKeysByPrefix(prefix) {
  return Object.keys(lightSplit.rest).filter((key) => key.startsWith(prefix));
}

function buildTypographySection() {
  const sizeKeys = restKeysByPrefix('font/size/');
  const rows = sizeKeys
    .map((key) => {
      const step = key.split('/')[2];
      const sizeVar = cssVarName('eds', key.split('/'));
      const lineHeightKey = `font/line-height/${step}`;
      const lineHeightVar = lightSplit.rest[lineHeightKey]
        ? `line-height: var(${cssVarName('eds', lineHeightKey.split('/'))});`
        : '';
      return `        <div class="type-row">
          <code class="type-step">${escapeHtml(step)}</code>
          <p style="font-size: var(${sizeVar}); ${lineHeightVar} font-family: var(--eds-f-family-display); margin: 0;">
            The quick brown fox jumps over the lazy dog
          </p>
        </div>`;
    })
    .join('\n');

  const familyKeys = restKeysByPrefix('font/family/');
  const families = familyKeys
    .map((key) => {
      const varName = cssVarName('eds', key.split('/'));
      const name = key.split('/')[2];
      return `        <div class="type-row">
          <code class="type-step">${escapeHtml(name)}</code>
          <p style="font-family: var(${varName}); margin: 0;">
            The quick brown fox jumps over the lazy dog
          </p>
        </div>`;
    })
    .join('\n');

  return `      <div class="group">
        <h3>family</h3>
        <div class="type-list">
${families}
        </div>
      </div>
      <div class="group">
        <h3>size / line-height</h3>
        <div class="type-list">
${rows}
        </div>
      </div>`;
}

function buildScaleSection(prefix, renderPreview) {
  const keys = restKeysByPrefix(prefix);
  return keys
    .map((key) => {
      const segments = key.split('/');
      const step = segments[segments.length - 1];
      const varName = cssVarName('eds', segments);
      return `        <div class="scale-row">
          <code class="scale-step">${escapeHtml(step)}</code>
          ${renderPreview(varName)}
          <code class="scale-var">${varName}</code>
        </div>`;
    })
    .join('\n');
}

function buildShadowSection() {
  const composites = buildShadowComposites(lightSplit.color, lightSplit.rest);
  return Object.keys(composites)
    .map((level) => {
      const varName = cssVarName('eds', ['shadow', 'elevation', level]);
      return `        <div class="scale-row">
          <code class="scale-step">${escapeHtml(level)}</code>
          <div class="shadow-box" style="box-shadow: var(${varName});"></div>
          <code class="scale-var">${varName}</code>
        </div>`;
    })
    .join('\n');
}

function buildShowcaseHtml() {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>EDS design tokens</title>
    <link rel="stylesheet" href="tokens.css" />
    <style>
      /* CDN-only source (no local fallback woff2, unlike ec.scss's
         @font-face - this showcase has no asset-copy build step to land
         a local file next to it). Real font loading belongs in a future
         eds preset, mirroring src/presets/ec/src/ec.scss. */
      @font-face {
        font-family: 'Inter';
        src: url('https://webtools.europa.eu/fonts/inter/InterVariable.woff2')
          format('woff2');
        font-weight: 100 900;
        font-style: normal;
        font-display: swap;
      }
      @font-face {
        font-family: 'Inter';
        src: url('https://webtools.europa.eu/fonts/inter/InterVariable-Italic.woff2')
          format('woff2');
        font-weight: 100 900;
        font-style: italic;
        font-display: swap;
      }
      * {
        box-sizing: border-box;
      }
      body {
        margin: 0;
        padding: var(--eds-sp-xl);
        background: var(--eds-c-surface-elevation-default);
        color: var(--eds-c-foreground-default);
        font-family: var(--eds-f-family-paragraph), arial, sans-serif;
      }
      header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: var(--eds-sp-m);
        margin-bottom: var(--eds-sp-xl);
        padding-bottom: var(--eds-sp-m);
        border-bottom: var(--eds-bw-xs) solid var(--eds-c-border-divider);
      }
      h1 {
        font-size: var(--eds-f-size-2xl);
        margin: 0;
      }
      h2 {
        font-size: var(--eds-f-size-xl);
        margin: var(--eds-sp-2xl) 0 var(--eds-sp-m);
      }
      h3 {
        font-size: var(--eds-f-size-s);
        text-transform: uppercase;
        letter-spacing: 0.04em;
        color: var(--eds-c-foreground-subtle);
        margin: 0 0 var(--eds-sp-s);
      }
      button {
        font: inherit;
        padding: var(--eds-sp-xs) var(--eds-sp-m);
        border-radius: var(--eds-br-s);
        border: var(--eds-bw-xs) solid var(--eds-c-border-default);
        background: var(--eds-c-surface-elevation-default);
        color: var(--eds-c-foreground-default);
        cursor: pointer;
      }
      section {
        margin-bottom: var(--eds-sp-2xl);
      }
      .group {
        margin-bottom: var(--eds-sp-xl);
      }
      .swatch-grid {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(9.5rem, 1fr));
        gap: var(--eds-sp-m);
      }
      .swatch-color {
        height: 3.5rem;
        border-radius: var(--eds-br-s);
        border: var(--eds-bw-xs) solid var(--eds-c-border-divider);
      }
      .swatch-label {
        font-size: var(--eds-f-size-xs);
        margin-top: var(--eds-sp-3xs);
      }
      .swatch-var {
        font-size: var(--eds-f-size-2xs);
        color: var(--eds-c-foreground-subtler);
        word-break: break-all;
      }
      .type-list,
      .scale-list {
        display: flex;
        flex-direction: column;
        gap: var(--eds-sp-s);
      }
      .type-row,
      .scale-row {
        display: grid;
        grid-template-columns: 5rem 1fr 14rem;
        align-items: center;
        gap: var(--eds-sp-m);
      }
      .type-step,
      .scale-step,
      .scale-var {
        font-size: var(--eds-f-size-2xs);
        color: var(--eds-c-foreground-subtler);
      }
      .scale-bar {
        height: var(--eds-sz-m);
        background: var(--eds-c-surface-primary-default);
        border-radius: var(--eds-br-xs);
      }
      .shape-box {
        width: var(--eds-sz-9xl);
        height: var(--eds-sz-6xl);
        background: var(--eds-c-surface-primary-subtle);
      }
      .shadow-box {
        width: var(--eds-sz-9xl);
        height: var(--eds-sz-6xl);
        background: var(--eds-c-surface-elevation-default);
        border-radius: var(--eds-br-s);
      }
      .opacity-box {
        width: var(--eds-sz-9xl);
        height: var(--eds-sz-6xl);
        border-radius: var(--eds-br-s);
        background: var(--eds-c-surface-primary-default);
        background-image: linear-gradient(
            45deg,
            #80808033 25%,
            transparent 25%
          ),
          linear-gradient(-45deg, #80808033 25%, transparent 25%),
          linear-gradient(45deg, transparent 75%, #80808033 75%),
          linear-gradient(-45deg, transparent 75%, #80808033 75%);
        background-size: 1rem 1rem;
        background-position:
          0 0,
          0 0.5rem,
          0.5rem -0.5rem,
          -0.5rem 0px;
      }
    </style>
  </head>
  <body>
    <header>
      <h1>EDS design tokens</h1>
      <button type="button" id="theme-toggle">Toggle dark mode</button>
    </header>

    <section>
      <h2>Color</h2>
${buildColorSections()}
    </section>

    <section>
      <h2>Typography</h2>
${buildTypographySection()}
    </section>

    <section>
      <h2>Spacing</h2>
      <div class="scale-list">
${buildScaleSection(
  'spacing/',
  (varName) => `<div class="scale-bar" style="width: var(${varName});"></div>`,
)}
      </div>
    </section>

    <section>
      <h2>Sizing</h2>
      <div class="scale-list">
${buildScaleSection(
  'sizing/',
  (varName) => `<div class="scale-bar" style="width: var(${varName});"></div>`,
)}
      </div>
    </section>

    <section>
      <h2>Border radius</h2>
      <div class="scale-list">
${buildScaleSection(
  'border-radius/',
  (varName) =>
    `<div class="shape-box" style="border-radius: var(${varName});"></div>`,
)}
      </div>
    </section>

    <section>
      <h2>Border width</h2>
      <div class="scale-list">
${buildScaleSection(
  'border-width/',
  (varName) =>
    `<div class="shape-box" style="border: var(${varName}) solid var(--eds-c-border-default);"></div>`,
)}
      </div>
    </section>

    <section>
      <h2>Shadow</h2>
      <div class="scale-list">
${buildShadowSection()}
      </div>
    </section>

    <section>
      <h2>Opacity</h2>
      <div class="scale-list">
${buildScaleSection(
  'opacity/',
  (varName) =>
    `<div class="opacity-box" style="opacity: var(${varName});"></div>`,
)}
      </div>
    </section>

    <script>
      const toggle = document.getElementById('theme-toggle');
      const root = document.documentElement;
      toggle.addEventListener('click', () => {
        const isDark = root.getAttribute('data-theme') === 'dark';
        root.setAttribute('data-theme', isDark ? 'light' : 'dark');
      });
    </script>
  </body>
</html>
`;
}

// -----------------------------------------------------------------------
// Write output
// -----------------------------------------------------------------------

async function main() {
  fs.mkdirSync(MAPS_DIR, { recursive: true });

  fs.writeFileSync(
    path.join(MAPS_DIR, 'primitives.scss'),
    buildPrimitivesScss(),
  );
  fs.writeFileSync(path.join(MAPS_DIR, 'color.scss'), buildColorMapsScss());
  fs.writeFileSync(
    path.join(MAPS_DIR, 'spacing.scss'),
    buildInvariantScss(
      'eds',
      lightSplit.rest,
      ['spacing', 'sizing'],
      '// Mode-invariant spacing / sizing scale.',
    ),
  );
  fs.writeFileSync(
    path.join(MAPS_DIR, 'typography.scss'),
    buildInvariantScss(
      'eds',
      lightSplit.rest,
      ['font'],
      '// Mode-invariant typography scale.',
    ),
  );
  fs.writeFileSync(
    path.join(MAPS_DIR, 'shape.scss'),
    buildInvariantScss(
      'eds',
      lightSplit.rest,
      ['border-radius', 'border-width'],
      '// Mode-invariant border-radius / border-width scale.',
    ),
  );
  fs.writeFileSync(
    path.join(MAPS_DIR, 'opacity.scss'),
    buildInvariantScss(
      'eds',
      lightSplit.rest,
      ['opacity'],
      '// Mode-invariant opacity scale.',
    ),
  );
  fs.writeFileSync(
    path.join(ROOT, '_custom-properties.scss'),
    buildCustomPropertiesScss(),
  );
  fs.writeFileSync(
    path.join(ROOT, 'tokens/tokens.json'),
    `${JSON.stringify(buildTokensJson(), null, 2)}\n`,
  );

  fs.mkdirSync(SHOWCASE_DIR, { recursive: true });
  fs.writeFileSync(path.join(SHOWCASE_DIR, 'tokens.css'), buildTokensCss());
  fs.writeFileSync(path.join(SHOWCASE_DIR, 'index.html'), buildShowcaseHtml());

  // Re-format everything this script just wrote with the repo's Prettier
  // config, so generated output always matches `pnpm pretty-check`.
  const generatedFiles = [
    path.join(MAPS_DIR, 'primitives.scss'),
    path.join(MAPS_DIR, 'color.scss'),
    path.join(MAPS_DIR, 'spacing.scss'),
    path.join(MAPS_DIR, 'typography.scss'),
    path.join(MAPS_DIR, 'shape.scss'),
    path.join(MAPS_DIR, 'opacity.scss'),
    path.join(ROOT, '_custom-properties.scss'),
    path.join(ROOT, 'tokens/tokens.json'),
    path.join(SHOWCASE_DIR, 'tokens.css'),
    path.join(SHOWCASE_DIR, 'index.html'),
  ];
  const prettier = require(
    require.resolve('prettier', { paths: [ROOT, path.join(ROOT, '../../..')] }),
  );
  await Promise.all(
    generatedFiles.map(async (file) => {
      const source = fs.readFileSync(file, 'utf8');
      const config = (await prettier.resolveConfig(file)) || {};
      const formatted = await prettier.format(source, {
        ...config,
        filepath: file,
      });
      fs.writeFileSync(file, formatted);
    }),
  );
  console.log('Generated eds theme tokens:');

  console.log(`  - ${Object.keys(primitives).length} primitives`);

  console.log(
    `  - ${Object.keys(light).length} semantic tokens per mode (light/dark)`,
  );
}

main();
