module.exports = {
  logo: {
    title: 'European Commission',
    alt: 'European Commission logo',
    href: '/example',
    language: 'en',
  },
  loginToggle: {
    labelNotLogged: 'Log in',
    hrefNotLogged: '/example',
    labelLogged: 'Logged in',
    hrefLogged: '/example',
  },
  loginBox: {
    id: 'login-box-id',
    description: 'Logged in as <last name>, <first name>',
    label: 'Log out',
    href: '/example',
  },
  languageSelector: {
    href: '/example',
    label: 'English',
    code: 'en',
    overlay: {
      closeLabel: 'Close',
      title: 'Select your language',
      items: [
        { lang: 'bg', label: 'български', href: '/example#language_bg' },
        { lang: 'es', label: 'español', href: '/example#language_es' },
        { lang: 'cs', label: 'čeština', href: '/example#language_cs' },
        { lang: 'da', label: 'dansk', href: '/example#language_da' },
        { lang: 'de', label: 'Deutsch', href: '/example#language_de' },
        { lang: 'et', label: 'eesti', href: '/example#language_et' },
        { lang: 'el', label: 'ελληνικά', href: '/example#language_el' },
        {
          lang: 'en',
          label: 'English',
          href: '/example#language_en',
          isActive: true,
        },
        { lang: 'fr', label: 'français', href: '/example#language_fr' },
        { lang: 'ga', label: 'Gaeilge', href: '/example#language_ga' },
        { lang: 'hr', label: 'hrvatski', href: '/example#language_hr' },
        { lang: 'it', label: 'italiano', href: '/example#language_it' },
        { lang: 'lv', label: 'latviešu', href: '/example#language_lv' },
        { lang: 'lt', label: 'lietuvių', href: '/example#language_lt' },
        { lang: 'hu', label: 'magyar', href: '/example#language_hu' },
        { lang: 'mt', label: 'Malti', href: '/example#language_mt' },
        { lang: 'nl', label: 'Nederlands', href: '/example#language_nl' },
        { lang: 'pl', label: 'polski', href: '/example#language_pl' },
        { lang: 'pt', label: 'português', href: '/example#language_pt' },
        { lang: 'ro', label: 'română', href: '/example#language_ro' },
        { lang: 'sk', label: 'slovenčina', href: '/example#language_sk' },
        { lang: 'sl', label: 'slovenščina', href: '/example#language_sl' },
        { lang: 'fi', label: 'suomi', href: '/example#language_fi' },
        { lang: 'sv', label: 'svenska', href: '/example#language_sv' },
      ],
    },
  },
  searchToggle: {
    label: 'Search',
    href: '/example',
  },
  searchForm: {
    id: 'search-form-id',
    textInputId: 'search-input-id',
    inputLabel: 'Search',
    buttonLabel: 'Search',
  },
  bannerTop: 'Class name',
  banner: 'Site name',
  menu: true,
};
