# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 21
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Label to use when marking an issue as stale
staleLabel: stale
# Issues with these labels will never be considered stale
exemptLabels:
  - 'WIP'
markComment: >
  Thanks for your contribution to ecl-twig!

  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.

  Issues that are labeled as `WIP` will not be automatically marked as stale.
