branches:
  exclude: [ gh-pages ]

matrix:
  TEST:
    - coding-conventions
    - functional

pipeline:
  install:
    image: node:latest
    commands:
      - yarn install --frozen-lockfile

  coding-conventions:
    image: node:latest
    commands:
      - yarn test:coding-conventions
    when:
      matrix:
        TEST: coding-conventions

  build:
    image: node:latest
    commands:
      - yarn dist
    when:
      event: [push]
      matrix:
        TEST: functional

  deploy-pages:
    image: node:latest
    secrets: [ GH_TOKEN ]
    commands:
      - ./scripts/deploy.sh
    when:
      event: [push]
      branch: master
      matrix:
        TEST: functional

  s3:
    image: garland/aws-cli-docker
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION ]
    commands:
      - cd ./dist
      - aws configure set default.s3.max_concurrent_requests 20
      - aws s3 cp --recursive --quiet . s3://inno-ecl/build/${DRONE_BUILD_NUMBER}/
      - echo "Transfer complete"
    when:
      event: [push]
      matrix:
        TEST: functional

  functional:
    image: node:latest
    secrets: [ SAUCE_USERNAME, SAUCE_ACCESS_KEY ]
    commands:
      - yarn test:functional;
    when:
      event: [push]
      matrix:
        TEST: functional
