clone:
  git:
    image: plugins/git
    commands:
      - git init
      - git remote add origin ${DRONE_REMOTE_URL}
      - git fetch --no-tags origin master
      - git checkout -qf master
      # If not on master
      - git fetch --no-tags origin ${DRONE_COMMIT_REF}
      - if [ "${DRONE_BUILD_EVENT}" == "push" ]; then 
          git reset --hard -q ${DRONE_COMMIT_SHA}; 
        else 
          git checkout -qf FETCH_HEAD; 
        fi
      - git status

pipeline:
  build:
    image: node:latest
    commands:
      - yarn install --frozen-lockfile

  coding-conventions:
    group: test
    image: node:latest
    commands:
      - yarn test:coding-conventions

  functional:
    group: test
    image: node:latest
    secrets: [ SAUCE_USERNAME, SAUCE_ACCESS_KEY ]
    commands:
      - yarn dist
      - yarn test:functional
    when:
      event: [push, tag, deployment]
