branches:
  exclude: [gh-pages]

clone:
  git:
    image: plugins/git
    commands:
      - git init
      - git remote add origin ${DRONE_REMOTE_URL}
      - git fetch --no-tags origin v1 ${DRONE_COMMIT_REF}
      - git checkout -qf v1;
      - if [ "${DRONE_BUILD_EVENT}" == "pull_request" ] || [ "${DRONE_BUILD_EVENT}" == "tag" ] ; then
        git checkout -qf FETCH_HEAD;
        else
        git checkout -qf ${DRONE_COMMIT_BRANCH};
        fi

matrix:
  TEST:
    - functional
    - conventions
    - examples

pipeline:
  install:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile

  conventions:
    image: node:dubnium
    commands:
      - yarn test:coding-conventions
      - yarn test:independent-sass
    when:
      event: [push]
      matrix:
        TEST: conventions

  examples:
    image: node:dubnium
    commands:
      - cd examples/webpack3 && yarn build --display=errors-only
      - cd ../webpack4 && yarn build --display=errors-only
      - cd ../webpack4-eu && yarn build --display=errors-only
    when:
      event: [push]
      matrix:
        TEST: examples

  build:
    image: node:dubnium
    commands:
      - if [ "${DRONE_BRANCH}" = "v1" ] || [ "${DRONE_BUILD_EVENT}" = "tag" ] || yarn updated --ignoreCache ; then
        yarn dist ;
        fi
    when:
      event: [push, tag]
      matrix:
        TEST: functional

  deploy-cdn:
    image: garland/aws-cli-docker
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION]
    commands:
      - if [ -d "./dist" ] ; then
        cd ./dist/packages ;
        aws configure set default.s3.max_concurrent_requests 20 ;
        aws s3 cp --recursive --quiet . s3://inno-ecl/ecl/${DRONE_TAG}/ ;
        echo "Transfer complete" ;
        fi
    when:
      event: [tag]
      matrix:
        TEST: functional

  deploy-pages:
    image: node:dubnium
    secrets: [GH_TOKEN]
    commands:
      - ./scripts/deploy.sh
    when:
      event: [push]
      branch: v1
      matrix:
        TEST: functional

  s3:
    image: garland/aws-cli-docker
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION]
    commands:
      - if [ -d "./dist" ] ; then
        cd ./dist/website ;
        aws configure set default.s3.max_concurrent_requests 20 ;
        aws s3 cp --recursive --quiet . s3://inno-ecl/build/${DRONE_BUILD_NUMBER}/ ;
        echo "Transfer complete" ;
        fi
    when:
      event: [push]
      matrix:
        TEST: functional

  functional:
    image: node:dubnium
    secrets: [SAUCE_USERNAME, SAUCE_ACCESS_KEY]
    commands:
      - if [ -d "./dist" ] ; then
        yarn test:functional ;
        fi
    when:
      event: [push]
      matrix:
        TEST: functional
