branches:
  exclude: [ gh-pages ]

clone:
  git:
    image: plugins/git
    commands:
      - git init
      - git config core.ignorecase false
      - git remote add origin ${DRONE_REMOTE_URL}
      - git fetch --no-tags origin next-v2 ${DRONE_COMMIT_REF}
      - git checkout -qf next-v2;
      - if [ "${DRONE_BUILD_EVENT}" == "pull_request" ] || [ "${DRONE_BUILD_EVENT}" == "tag" ] ; then
          git checkout -qf FETCH_HEAD;
        else
          git checkout -qf ${DRONE_COMMIT_BRANCH};
        fi

matrix:
  TEST:
    - conventions
    - examples

pipeline:
  install:
    image: node:9.11.1
    commands:
      - yarn install --frozen-lockfile

  conventions:
    image: node:9.11.1
    commands:
      - yarn test:coding-conventions
    when:
      matrix:
        TEST: conventions

  examples:
    image: node:9.11.1
    commands:
      - cd examples/webpack3 && yarn build --display=errors-only
      - cd ../webpack4 && yarn build --display=errors-only
      - cd ../webpack4-eu && yarn build --display=errors-only
    when:
      matrix:
        TEST: examples
