pipeline:
  # On PRs, checkout master (for tests)
  checkout-master:
    image: plugins/git
    commands:
      - git fetch --no-tags origin master
      - git checkout -qf master
      - git checkout -

  build:
    image: node:latest
    commands:
      - yarn install --frozen-lockfile

  coding-conventions:
    group: test
    image: node:latest
    commands:
      - yarn test:coding-conventions

  functional:
    group: test
    image: node:latest
    secrets: [ SAUCE_USERNAME, SAUCE_ACCESS_KEY ]
    commands:
      - yarn dist
      - yarn test:functional
    when:
      event: [push, tag, deployment]
