branches:
  exclude: [ gh-pages ]

clone:
  git:
    image: plugins/git
    commands:
      - git init
      - git config core.ignorecase false
      - git remote add origin ${DRONE_REMOTE_URL}
      - git fetch --no-tags origin master ${DRONE_COMMIT_REF}
      - git checkout -qf master;
      - if [ "${DRONE_BUILD_EVENT}" == "pull_request" ] || [ "${DRONE_BUILD_EVENT}" == "tag" ] ; then
          git checkout -qf FETCH_HEAD;
        else
          git checkout -qf ${DRONE_COMMIT_BRANCH};
        fi

matrix:
  TEST:
    - deploy-pages
    - conventions
    - examples
    - visual-regression

pipeline:
  conventions:
    image: node:9.11.1
    commands:
      - yarn install --frozen-lockfile
      - yarn test:coding-conventions
    when:
      matrix:
        TEST: conventions

  examples:
    image: node:9.11.1
    commands:
      - yarn install --frozen-lockfile
      - cd examples/webpack3 && yarn build --display=errors-only
      - cd ../webpack4 && yarn build --display=errors-only
      - cd ../webpack4-eu && yarn build --display=errors-only
    when:
      matrix:
        TEST: examples

  visual-regression:
    image: hivelocityinc/docker-node-chromium
    shm_size: 1g
    commands:
      - yarn install --frozen-lockfile
      - cd src/systems/ec/implementations/react/storybook
      - yarn build
      - yarn test
    when:
      event: [push]
      matrix:
        TEST: visual-regression

  build:
    image: hivelocityinc/docker-node-chromium
    shm_size: 1g
    commands:
      - yarn install --frozen-lockfile
      - if [ "${DRONE_BRANCH}" = "master" ] || yarn updated --ignoreCache ; then
          yarn dist ;
        fi
    when:
      event: [push]
      branch: master
      matrix:
        TEST: deploy-pages

  deploy-pages:
    image: node:9.11.1
    secrets: [ GH_TOKEN ]
    commands:
      - ./scripts/deploy.sh
    when:
      event: [push]
      branch: master
      matrix:
        TEST: deploy-pages
