branches:
  exclude: [ gh-pages ]

matrix:
  TEST:
    - audit
    - conventions
    - examples
    - deploy-tag

pipeline:
  install:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile

  audit:
    image: node:dubnium
    commands:
      - yarn audit
    when:
      matrix:
        TEST: audit

  conventions:
    image: node:dubnium
    commands:
      - yarn test:coding-conventions
    when:
      matrix:
        TEST: conventions

  examples:
    image: node:dubnium
    commands:
      - cd examples/webpack4 && yarn build --display=errors-only
      - cd ../webpack4-eu && yarn build --display=errors-only
    when:
      matrix:
        TEST: examples

  build:
    image: node:dubnium
    commands:
      - yarn clean
      - yarn dist:presets
    when:
      event: [tag]
      matrix:
        TEST: deploy-tag

  deploy-cdn:
    image: garland/aws-cli-docker
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION]
    commands:
      - if [ -d "./dist" ] ; then
        cd ./dist/packages ;
        aws configure set default.s3.max_concurrent_requests 20 ;
        aws s3 cp --recursive --quiet . s3://inno-ecl/ecl/${DRONE_TAG}/ ;
        echo "Transfer complete" ;
        fi
    when:
      event: [tag]
      matrix:
        TEST: deploy-tag
