# On PRs, checkout master (for tests, push only)
clone:
  git:
    image: plugins/git
    commands:
      - echo "${DRONE_PULL_REQUEST}"
      - echo "${DRONE_COMMIT_BRANCH}"
      - echo "$DRONE_PULL_REQUEST"
      - echo "$DRONE_COMMIT_BRANCH"
      - git fetch --no-tags origin master
      - git checkout -qf master
      - git checkout -
    when:
      branch:
        exclude: [master]
      event: [push]

pipeline:
  build:
    image: node:latest
    commands:
      - yarn install --frozen-lockfile

  coding-conventions:
    group: test
    image: node:latest
    commands:
      - yarn test:coding-conventions

  functional:
    group: test
    image: node:latest
    secrets: [ SAUCE_USERNAME, SAUCE_ACCESS_KEY ]
    commands:
      - yarn dist
      - yarn test:functional
    when:
      event: [push, tag, deployment]
