branches:
  exclude: [ gh-pages ]

matrix:
  TEST:
    - audit
    - conventions
    - examples

pipeline:
  install:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile

  audit:
    image: node:dubnium
    commands:
      - yarn audit
    when:
      matrix:
        TEST: audit

  conventions:
    image: node:dubnium
    commands:
      - yarn test:coding-conventions
    when:
      matrix:
        TEST: conventions

  examples:
    image: node:dubnium
    commands:
      - cd examples/webpack3 && yarn build --display=errors-only
      - cd ../webpack4 && yarn build --display=errors-only
      - cd ../webpack4-eu && yarn build --display=errors-only
    when:
      matrix:
        TEST: examples
