branches:
  exclude: [gh-pages]

clone:
  git:
    image: plugins/git
    commands:
      - git init
      - git remote add origin ${DRONE_REMOTE_URL}
      - git fetch origin v1 ${DRONE_COMMIT_REF}
      - git checkout -qf v1;
      - if [ "${DRONE_BUILD_EVENT}" == "pull_request" ] || [ "${DRONE_BUILD_EVENT}" == "tag" ] ; then
        git checkout -qf FETCH_HEAD;
        else
        git checkout -qf ${DRONE_COMMIT_BRANCH};
        fi

pipeline:
  install:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile
    when:
      event: [push, pull_request, deployment]

  build:
    image: node:dubnium
    commands:
      - if [ "${DRONE_BRANCH}" = "v1" ] || [ "${DRONE_BUILD_EVENT}" = "push" ] || [ "${DRONE_BUILD_EVENT}" = "deployment" ] || yarn updated --ignoreCache ; then
        yarn dist ;
        fi
    when:
      event: [push, deployment]

  deploy-cdn:
    image: garland/aws-cli-docker
    group: s3
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION]
    commands:
      - if [ -d "./dist" ] ; then
        cd ./dist/packages ;
        aws configure set default.s3.max_concurrent_requests 20 ;
        aws s3 cp --recursive --quiet . s3://inno-ecl/ecl/${DRONE_TAG}/ ;
        echo "Transfer complete" ;
        fi
    when:
      event: [tag]

  s3:
    image: garland/aws-cli-docker
    group: s3
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION]
    commands:
      - if [ -d "./dist" ] ; then
        cd ./dist/website ;
        aws configure set default.s3.max_concurrent_requests 20 ;
        aws s3 cp --recursive --quiet . s3://inno-ecl/build/${DRONE_BUILD_NUMBER}/ ;
        echo "Transfer complete" ;
        fi
    when:
      event: [push]

  conventions:
    image: node:dubnium
    group: tests
    commands:
      - yarn test:coding-conventions
      - yarn test:independent-sass
    when:
      event: [push]

  examples:
    image: node:dubnium
    group: tests
    commands:
      - cd examples/webpack3 && yarn build --display=errors-only
      - cd ../webpack4 && yarn build --display=errors-only
      - cd ../webpack4-eu && yarn build --display=errors-only
    when:
      event: [push]

  functional:
    image: node:dubnium
    group: tests
    secrets: [SAUCE_USERNAME, SAUCE_ACCESS_KEY]
    commands:
      - if [ -d "./dist" ] ; then
        yarn test:functional ;
        fi
    when:
      event: [push]

  deploy-netlify-preview:
    image: buildkite/puppeteer:latest
    secrets: [gh_token, netlify_auth_token, netlify_site]
    commands:
      - './node_modules/.bin/netlify deploy --site $${NETLIFY_SITE} --message "Drone build: ${CI_BUILD_NUMBER}" --json > netlify_deployment_result.json'
      - node scripts/set-netlify-deployment-status.js
    when:
      status: [failure, success]
      event: [push]

  # Trigger deploy event on Github
  create-deployment-event:
    image: fpfis/drone-plugin-github-deploy
    state: create
    deploy_environment: v1
    secrets: [github_api_token]
    automerge: false
    when:
      event: [tag]

  deploy-v1:
    image: drillster/drone-rsync
    secrets: [rsync_key, MGMT_IP]
    hosts: [$MGMT_IP]
    user: fpfis
    source: ./dist/website
    target: '/ec/local/home/fpfis/reference/php-clusters/multisite/production/cluster00/sources/static/europa-component-library/${DRONE_TAG}'
    script:
      - export GIT_FPFIS_AUTHOR="Drone ec.deploy.fpfis.eu"
      - cd /ec/local/home/fpfis/reference/php-clusters/multisite/production/cluster00/sources/static/europa-component-library
      - git add -A .
      - git commit -m "Deployed ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}@${DRONE_TAG} from drone build ${DRONE_BUILD_NUMBER}." .
      - git push 'nas-reference' 'master'
    when:
      event: deployment
      environment: v1
