version: 3

pullapprove_conditions:
  - condition: "'wip' not in labels"
    unmet_status: pending
    explanation: 'This PR is a work in progress'

groups:
  code-review:
    reviews:
      # -1 will require that all pending requests are approved
      required: -1
    reviewers:
      teams:
        - inno
