version: 2

always_pending:
  labels:
    - wip
  explanation: 'This PR is a work in progress'

always_rejected:
  title_regex: '^(?!(chore|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+\))?\:\s(\S+)).*$'
  explanation: 'Invalid title. Please read our conventions: https://github.com/ec-europa/europa-component-library/blob/master/docs/conventions/git.md'

groups:
  code-review:
    required: 1
    github_reviews:
      enabled: true
    approve_by_comment:
      enabled: false
    author_approval:
      ignored: true
    reset_on_push:
      enabled: true
    reset_on_reopened:
      enabled: true
    teams:
      - inno
