version: 3

pullapprove_conditions:
  - condition: "'process: WIP' not in labels"
    unmet_status: pending
    explanation: 'This PR is a work in progress'
  - condition: "'process: on hold' not in labels"
    unmet_status: pending
    explanation: 'This PR is on hold'

groups:
  # when 'process: review needed' is added, automatically request a review from
  code-review:
    conditions:
      - "'process: review needed' in labels"
    reviews:
      required: 1
      request: -1
    reviewers:
      teams:
        - ecl-reviewers
  # all pending requests must be approved
  all_requests:
    reviews:
      required: 1
