# https://zappr.readthedocs.io/en/latest/setup

approvals:
# at least one approval is needed
  minimum: 1
# ignore approvals from PR opener and last committer
  ignore: both
# only collaborators can approve
  from:
    collaborators: true
