packages:
  - "src/components/**"
  - "src/compositions/*"
  - "src/page-example/*"
  - "src/utilities/*"
  - "src/layout/*"
  - "src/playground/**"
  - "src/resources/*"
  - "src/specs/**"
  - "src/themes/*"
  - "src/presets/*"
  - "src/tools/*"
  - "src/website"
