packages:
  - "src/implementations/**"
  - "src/playground/**"
  - "src/resources/*"
  - "src/specs/**"
  - "src/themes/*"
  - "src/presets/*"
  - "src/tools/*"
  - "src/website"
hoist:
  - "@storybook/addon-cssresources"
  - "react-snap"
