backend:
  name: git-gateway
  repo: ec-europa/europa-component-library
  branch: netlify-cms-demo
  base_url: https://ecl-preview-1883--europa-component-library.netlify.app
  extension: md
  squash_merges: true
  commit_messages:
    create: 'feat({{collection}}): create {{collection}} “{{slug}}”'
    update: 'feat({{collection}}): update {{collection}} “{{slug}}”'
    delete: 'feat({{collection}}): delete {{collection}} “{{slug}}”'
    uploadMedia: 'Upload “{{path}}”'
    deleteMedia: 'Delete “{{path}}”'

#local_backend: true
media_folder: cms-images
publish_mode: editorial_workflow

collections:
  - label: 'Docs'
    name: 'docs'
    files:
      - label: 'Landing page'
        name: 'index'
        file: 'src/website/src/pages/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
  - label: 'Usage pages for components'
    name: 'EC usage_pages'
    files:
      - label: 'Accordion'
        name: 'ec_accordion'
        file: 'src/website/src/pages/ec/components/accordion/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Blockquote'
        name: 'ec_blockquote'
        file: 'src/website/src/pages/ec/components/blockquote/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Button'
        name: 'ec_button'
        file: 'src/website/src/pages/ec/components/button/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Card'
        name: 'ec_card'
        file: 'src/website/src/pages/ec/components/card/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Checkbox'
        name: 'ec_checkbox'
        file: 'src/website/src/pages/ec/components/forms/checkbox/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Date block'
        name: 'ec_date_block'
        file: 'src/website/src/pages/ec/components/date-block/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Datepicker'
        name: 'ec_datepicker'
        file: 'src/website/src/pages/ec/components/forms/datepicker/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Expandable'
        name: 'ec_expandable'
        file: 'src/website/src/pages/ec/components/expandable/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Fact & figures'
        name: 'ec_fact_figures'
        file: 'src/website/src/pages/ec/components/fact-figures/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'File'
        name: 'ec_file'
        file: 'src/website/src/pages/ec/components/file/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'File Upload'
        name: 'ec_file_upload'
        file: 'src/website/src/pages/ec/components/forms/file-upload/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Footer Core'
        name: 'ec_footer_core'
        file: 'src/website/src/pages/ec/core_template/footer/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Footer Harmonised Group1'
        name: 'ec_footer_harmonised_g1'
        file: 'src/website/src/pages/ec/harmonised_template/footer/docs/group1.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Footer Harmonised Group2'
        name: 'ec_footer_harmonised_g2'
        file: 'src/website/src/pages/ec/harmonised_template/footer/docs/group2.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Footer Harmonised Group3'
        name: 'ec_footer_harmonised_g3'
        file: 'src/website/src/pages/ec/harmonised_template/footer/docs/group3.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Footer Standardised'
        name: 'ec_footer_standardised'
        file: 'src/website/src/pages/ec/standardised_template/footer/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Gallery'
        name: 'ec_gallery'
        file: 'src/website/src/pages/ec/components/media/gallery/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Hero Banner'
        name: 'ec_hero_banner'
        file: 'src/website/src/pages/ec/components/banners/hero-banner/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Icon'
        name: 'ec_icon'
        file: 'src/website/src/pages/ec/components/icon/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Inpage navigation'
        name: 'ec_inpage_navigation'
        file: 'src/website/src/pages/ec/components/navigation/inpage-navigation/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Label'
        name: 'ec_label'
        file: 'src/website/src/pages/ec/components/label/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Language list'
        name: 'ec_language_list'
        file: 'src/website/src/pages/ec/components/language-list/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Link'
        name: 'ec_link'
        file: 'src/website/src/pages/ec/components/navigation/link/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'List'
        name: 'ec_list'
        file: 'src/website/src/pages/ec/components/list/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Media container'
        name: 'ec_media_container'
        file: 'src/website/src/pages/ec/components/media/media-container/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Menu'
        name: 'ec_menu'
        file: 'src/website/src/pages/ec/components/navigation/menu/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Message'
        name: 'ec_message'
        file: 'src/website/src/pages/ec/components/message/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Page Banner'
        name: 'ec_page_banner'
        file: 'src/website/src/pages/ec/components/banners/page-banner/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Page Header Core'
        name: 'ec_page_header_core'
        file: 'src/website/src/pages/ec/core-template/page-header/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Page Header Harmonised Group 1'
        name: 'ec_page_header_harmonised_g1'
        file: 'src/website/src/pages/ec/harmonised-templates/page-header/docs/group1.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Page Header Harmonised Group 2'
        name: 'ec_page_header_harmonised_g2'
        file: 'src/website/src/pages/ec/harmonised-templates/page-header/docs/group2.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Page Header Standardised'
        name: 'ec_page_header_standardised'
        file: 'src/website/src/pages/ec/standardised_template/page-header/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Pagination'
        name: 'ec_pagination'
        file: 'src/website/src/pages/ec/components/navigation/pagination/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Radio'
        name: 'ec_radio'
        file: 'src/website/src/pages/ec/components/forms/radio/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Select'
        name: 'ec_select'
        file: 'src/website/src/pages/ec/components/forms/select/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Site Header Core'
        name: 'ec_site_header_core'
        file: 'src/website/src/pages/ec/core_template/site-header/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Site Header Harmonised Group1'
        name: 'ec_site_header_harmonised_g1'
        file: 'src/website/src/pages/ec/harmonised_template/site-header/docs/group1.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Site Header Harmonised Group2'
        name: 'ec_site_header_harmonised_g2'
        file: 'src/website/src/pages/ec/harmonised_template/site-header/docs/group2.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Site Header Standardised'
        name: 'ec_site_header_standardised'
        file: 'src/website/src/pages/ec/standardised_template/site-header/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Skip link'
        name: 'ec_skip_link'
        file: 'src/website/src/pages/ec/components/navigation/skip-link/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Social media follow'
        name: 'ec_social_media_follow'
        file: 'src/website/src/pages/ec/components/social-media-follow/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Social media share'
        name: 'ec_social_media_share'
        file: 'src/website/src/pages/ec/components/social-media-share/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Table'
        name: 'ec_table'
        file: 'src/website/src/pages/ec/components/forms/table/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Tag'
        name: 'ec_tag'
        file: 'src/website/src/pages/ec/components/forms/tag/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Textarea'
        name: 'ec_textarea'
        file: 'src/website/src/pages/ec/components/forms/text-area/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Text field'
        name: 'ec_text-field'
        file: 'src/website/src/pages/ec/components/forms/text-field/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Timeline'
        name: 'ec_timeline'
        file: 'src/website/src/pages/ec/components/timeline/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
  - label: 'EC pages for families templates'
    name: 'ec_usage_pages_templates'
    files:
      - label: 'EC Core template'
        name: 'ec_core_template'
        file: 'src/website/src/pages/ec/core-template/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Harmonised template Group 1'
        name: 'ec_harmonised_template_g1'
        file: 'src/website/src/pages/ec/harmonised-template/docs/group1.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Harmonised template Group 2'
        name: 'ec_harmonised_template_g2'
        file: 'src/website/src/pages/ec/harmonised-template/docs/group2.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Harmonised template Group 3'
        name: 'ec_harmonised_template_g3'
        file: 'src/website/src/pages/ec/harmonised-template/docs/group3.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Standardised template'
        name: 'ec_standardised_template'
        file: 'src/website/src/pages/ec/standardised-template/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
  - label: 'EC Compositions'
    name: 'ec_compositions'
    files:
      - label: 'Content item'
        name: 'ec_content_item'
        file: 'src/website/src/pages/ec/compositions/content-item/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Harmonised template Group 1'
        name: 'ec_harmonised_template_g1'
        file: 'src/website/src/pages/ec/harmonised-template/docs/group1.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Harmonised template Group 2'
        name: 'ec_harmonised_template_g2'
        file: 'src/website/src/pages/ec/harmonised-template/docs/group2.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Harmonised template Group 3'
        name: 'ec_harmonised_template_g3'
        file: 'src/website/src/pages/ec/harmonised-template/docs/group3.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Standardised template'
        name: 'ec_standardised_template'
        file: 'src/website/src/pages/ec/standardised-template/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
  - label: 'EC Utilities'
    name: 'ec_utilities'
    files:
      - label: 'Index'
        name: 'ec_utilities_index'
        file: 'src/website/src/pages/ec/utilities/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Background'
        name: 'ec_utilities_background'
        file: 'src/website/src/pages/ec/utilities/background/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Border'
        name: 'ec_utilities_border'
        file: 'src/website/src/pages/ec/utilities/border/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Clearfix'
        name: 'ec_utilities_clearfix'
        file: 'src/website/src/pages/ec/utilities/clearfix/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Dimension'
        name: 'ec_utilities_dimension'
        file: 'src/website/src/pages/ec/utilities/dimension/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Dimension'
        name: 'ec_utilities_disable_scroll'
        file: 'src/website/src/pages/ec/utilities/disablescroll/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Display'
        name: 'ec_utilities_display'
        file: 'src/website/src/pages/ec/utilities/display/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Float'
        name: 'ec_utilities_float'
        file: 'src/website/src/pages/ec/utilities/float/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Grid'
        name: 'ec_utilities_grid'
        file: 'src/website/src/pages/ec/utilities/layout/grid/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Stacks'
        name: 'ec_utilities_stacks'
        file: 'src/website/src/pages/ec/utilities/layout/stack/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Media'
        name: 'ec_utilities_media'
        file: 'src/website/src/pages/ec/utilities/media/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Print'
        name: 'ec_utilities_print'
        file: 'src/website/src/pages/ec/utilities/print/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Screen reader'
        name: 'ec_utilities_screen_reader'
        file: 'src/website/src/pages/ec/utilities/screen-reader/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Spacing'
        name: 'ec_utilities_spacing'
        file: 'src/website/src/pages/ec/utilities/spacing/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Typography'
        name: 'ec_utilities_typography'
        file: 'src/website/src/pages/ec/utilities/typography/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Z-index'
        name: 'ec_utilities_z_index'
        file: 'src/website/src/pages/ec/utilities/z-index/docs/usage.md'
        fields:
          - { label: Body, name: body, widget: markdown }
  - label: 'EC Guidelines'
    name: 'ec_guidelines'
    files:
      - label: 'Colours'
        name: 'ec_guidelines_colours'
        file: 'src/website/src/pages/ec/guidelines/colours/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Iconography'
        name: 'ec_guidelines_iconography'
        file: 'src/website/src/pages/ec/guidelines/iconography/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Images'
        name: 'ec_guidelines_images'
        file: 'src/website/src/pages/ec/guidelines/images/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Spacing'
        name: 'ec_guidelines_spacing'
        file: 'src/website/src/pages/ec/guidelines/spacing/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Typography'
        name: 'ec_guidelines_typography'
        file: 'src/website/src/pages/ec/guidelines/typography/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
  - label: 'EC Reources'
    name: 'ec_resources'
    files:
      - label: 'Eui'
        name: 'ec_resources_eui'
        file: 'src/website/src/pages/ec/resources/eui/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Glossary'
        name: 'ec_resources_glossary'
        file: 'src/website/src/pages/ec/resources/glossary/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: 'Webtools'
        name: 'ec_resources_webtools'
        file: 'src/website/src/pages/ec/resources/webtools/index.md'
        fields:
          - { label: Body, name: body, widget: markdown }
