// Exports every token map listed in tokens-manifest.scss to build/eds-tokens.json,
// preserving the nested map structure so designers can browse it at a glance.
//
// The manifest SCSS calls a custom `to-json()` function (registered below) with
// the full token tree; we walk the resulting Sass Value and convert it to plain
// JS data. Adding/removing a token map only requires editing tokens-manifest.scss.
const fs = require('fs');
const path = require('path');
const sass = require('sass');

const root = path.join(__dirname, '..');
const manifestPath = path.join(__dirname, 'tokens-manifest.scss');
const outPath = path.join(root, 'tokens.json');

function keyToJs(key) {
  return key instanceof sass.SassString ? key.text : String(valueToJs(key));
}

function colorToJs(color) {
  const r = color.channel('red');
  const g = color.channel('green');
  const b = color.channel('blue');
  const a = color.channel('alpha');
  const hex = (n) => Math.round(n).toString(16).padStart(2, '0');

  return a === 1
    ? `#${hex(r)}${hex(g)}${hex(b)}`
    : `rgba(${r}, ${g}, ${b}, ${a})`;
}

function numberToJs(number) {
  const units = number.numeratorUnits.toArray();

  return units.length ? `${number.value}${units.join('')}` : number.value;
}

function valueToJs(value) {
  if (value instanceof sass.SassMap) {
    const obj = {};

    for (const [key, sub] of value.contents) {
      obj[keyToJs(key)] = valueToJs(sub);
    }

    return obj;
  }

  if (value instanceof sass.SassList) {
    return value.asList.toArray().map(valueToJs);
  }

  if (value instanceof sass.SassColor) {
    return colorToJs(value);
  }

  if (value instanceof sass.SassNumber) {
    return numberToJs(value);
  }

  if (value instanceof sass.SassString) {
    return value.text;
  }

  if (value instanceof sass.SassBoolean) {
    return value.value;
  }

  if (value === sass.sassNull) {
    return null;
  }

  throw new Error(`Unsupported Sass value type for token export: ${value}`);
}

let tokens;

sass.compile(manifestPath, {
  functions: {
    'to-json($value)': (args) => {
      tokens = valueToJs(args[0]);

      return sass.sassNull;
    },
  },
});

if (!tokens) {
  throw new Error(
    'Token export produced no output — check tokens-manifest.scss',
  );
}

const output = {
  $comment:
    'AUTO-GENERATED by scripts/export-tokens.js from tokens-manifest.scss — do not edit by hand. Regenerate with `npm run export:tokens`.',
  ...tokens,
};

fs.writeFileSync(outPath, `${JSON.stringify(output, null, 2)}\n`);

console.log('Exported design tokens to tokens.json');
