// Simple content for demo
module.exports = {
  toggleLabelOpen: 'Menu',
  toggleLabelClose: 'Close',
  siteName: 'Site name',
  items: [
    { label: 'Home', href: '/example' },
    {
      label: 'Item 1',
      href: '/example',
      isCurrent: true,
      subItems: [
        { label: 'Item 1.1', href: '/example' },
        { label: 'Item 1.2', href: '/example' },
        { label: 'Item 1.3', href: '/example', isCurrent: true },
        { label: 'Item 1.4', href: '/example' },
        { label: 'Item 1.5', href: '/example' },
        { label: 'Item 1.6', href: '/example' },
        { label: 'Item 1.7', href: '/example' },
        { label: 'Item 1.8', href: '/example' },
        { label: 'Item 1.9', href: '/example' },
        { label: 'Item 1.10', href: '/example' },
        { label: 'Item 1.11', href: '/example' },
        { label: 'Item 1.12', href: '/example' },
        { label: 'Item 1.13', href: '/example' },
        { label: 'Item 1.14', href: '/example' },
        { label: 'Item 1.15', href: '/example' },
        { label: 'Item 1.16', href: '/example' },
      ],
    },
    {
      label: 'Item 2',
      href: '/example',
      subItems: [
        { label: 'Item 2.1', href: '/example' },
        { label: 'Item 2.2', href: '/example' },
        { label: 'Item 2.3', href: '/example' },
        { label: 'Item 2.4', href: '/example' },
        { label: 'Item 2.5', href: '/example' },
        { label: 'Item 2.6', href: '/example' },
        { label: 'Item 2.7', href: '/example' },
        { label: 'Item 2.8', href: '/example' },
        { label: 'Item 2.9', href: '/example' },
      ],
    },
    {
      label: 'Item 3',
      href: '/example',
      subItems: [
        { label: 'Item 3.1', href: '/example' },
        { label: 'Item 3.2', href: '/example' },
        { label: 'Item 3.3', href: '/example' },
      ],
    },
    {
      label: 'Item 4',
      href: '/example',
      subItems: [
        { label: 'Item 4.1', href: '/example' },
        { label: 'Item 4.2', href: '/example' },
        { label: 'Item 4.3 with a very long label', href: '/example' },
        { label: 'Item 4.4', href: '/example' },
        { label: 'Item 4.5', href: '/example' },
        { label: 'Item 4.6', href: '/example' },
        { label: 'Item 4.7', href: '/example' },
        { label: 'Item 4.8', href: '/example' },
        { label: 'Item 4.9', href: '/example' },
        { label: 'Item 4.10', href: '/example' },
        { label: 'Item 4.11', href: '/example' },
        { label: 'Item 4.12', href: '/example' },
        { label: 'Item 4.13', href: '/example' },
        { label: 'Item 4.14', href: '/example' },
      ],
    },
    {
      label: 'Item 5',
      href: '/example',
      subItems: [
        { label: 'Item 5.1', href: '/example' },
        { label: 'Item 5.2', href: '/example' },
        { label: 'Item 5.3', href: '/example' },
        { label: 'Item 5.4', href: '/example' },
        { label: 'Item 5.5', href: '/example' },
        { label: 'Item 5.6', href: '/example' },
        { label: 'Item 5.7', href: '/example' },
        { label: 'Item 5.8', href: '/example' },
        { label: 'Item 5.9', href: '/example' },
        { label: 'Item 5.10', href: '/example' },
        { label: 'Item 5.11', href: '/example' },
        { label: 'Item 5.12', href: '/example' },
        { label: 'Item 5.13', href: '/example' },
        { label: 'Item 5.14', href: '/example' },
        { label: 'Item 5.15', href: '/example' },
        { label: 'Item 5.16', href: '/example' },
      ],
    },
    {
      label: 'Item 6',
      href: '/example',
      subItems: [
        { label: 'Item 6.1', href: '/example' },
        { label: 'Item 6.2', href: '/example' },
        { label: 'Item 6.3', href: '/example' },
        { label: 'Item 6.4', href: '/example' },
        { label: 'Item 6.5', href: '/example' },
        { label: 'Item 6.6', href: '/example' },
        { label: 'Item 6.7', href: '/example' },
        { label: 'Item 6.8', href: '/example' },
        { label: 'Item 6.9', href: '/example' },
        { label: 'Item 6.10', href: '/example' },
        { label: 'Item 6.11', href: '/example' },
        { label: 'Item 6.12', href: '/example' },
        { label: 'Item 6.13', href: '/example' },
        { label: 'Item 6.14', href: '/example' },
        { label: 'Item 6.15', href: '/example' },
        { label: 'Item 6.16', href: '/example' },
      ],
    },
    {
      label: 'Item 7 with a long label',
      href: '/example',
      subItems: [
        { label: 'Item 7.1', href: '/example' },
        { label: 'Item 7.2', href: '/example' },
        { label: 'Item 7.3', href: '/example' },
        { label: 'Item 7.4 with a very long label', href: '/example' },
        { label: 'Item 7.5', href: '/example' },
        { label: 'Item 7.6', href: '/example' },
        { label: 'Item 7.7', href: '/example' },
        { label: 'Item 7.8', href: '/example' },
        { label: 'Item 7.9', href: '/example' },
        { label: 'Item 7.10', href: '/example' },
        { label: 'Item 7.11', href: '/example' },
        { label: 'Item 7.12', href: '/example' },
        { label: 'Item 7.13', href: '/example' },
        { label: 'Item 7.14', href: '/example' },
        { label: 'Item 7.15', href: '/example' },
        { label: 'Item 7.16', href: '/example' },
      ],
    },
  ],
};
