module.exports = {
  id: 'example-input-id-1',
  name: 'example-input-id-1',
  label: 'Label',
  placeholder: 'DD-MM-YYYY',
  autoinit: true,
  default_value: '01-10-2020',
  helper_text: "This is the input's helper text.",
  invalid_icon: {
    path: '/icons.svg',
    type: 'notifications',
    name: 'error',
    size: 'm',
  },
  invalid_text: 'This is the error message',
  optional_text: ' (optional)',
  required_text: '*',
  icons_path: '/icons.svg',
  required: true,
};
