module.exports = {
  items: [
    {
      label: 'български',
      path: '/example',
      aria_label: '',
      lang: 'bg',
    },
    {
      label: 'español',
      path: '/example',
      aria_label: '',
      lang: 'es',
    },
    {
      label: 'čeština',
      path: '/example',
      aria_label: '',
      lang: 'cs',
    },
    {
      label: 'dansk',
      path: '/example',
      aria_label: '',
      lang: 'da',
    },
    {
      label: 'Deutsch',
      path: '/example',
      aria_label: '',
      lang: 'de',
    },
    {
      label: 'eesti',
      path: '/example',
      aria_label: '',
      lang: 'et',
    },
    {
      label: 'ελληνικά',
      path: '/example',
      aria_label: '',
      lang: 'el',
    },
    {
      label: 'English',
      path: '/example',
      aria_label: '',
      active: true,
      lang: 'en',
    },
    {
      label: 'français',
      path: '/example',
      aria_label: '',
      lang: 'fr',
    },
    {
      label: 'Gaeilge',
      path: '/example',
      aria_label: '',
      lang: 'ga',
    },
    {
      label: 'hrvatski',
      path: '/example',
      aria_label: '',
      lang: 'hr',
    },
    {
      label: 'italiano',
      path: '/example',
      aria_label: '',
      lang: 'it',
    },
    {
      label: 'latviešu',
      path: '/example',
      aria_label: '',
      lang: 'lv',
    },
    {
      label: 'lietuvių',
      path: '/example',
      aria_label: '',
      lang: 'lt',
    },
    {
      label: 'magyar',
      path: '/example',
      aria_label: '',
      lang: 'hu',
    },
    {
      label: 'Malti',
      path: '/example',
      aria_label: '',
      lang: 'mt',
    },
    {
      label: 'Nederlands',
      path: '/example',
      aria_label: '',
      lang: 'nl',
    },
    {
      label: 'polski',
      path: '/example',
      aria_label: '',
      lang: 'pl',
    },
    {
      label: 'português',
      path: '/example',
      aria_label: '',
      lang: 'pt',
    },
    {
      label: 'română',
      path: '/example',
      aria_label: '',
      lang: 'ro',
    },
    {
      label: 'slovenčina',
      path: '/example',
      aria_label: '',
      lang: 'sk',
    },
    {
      label: 'slovenščina',
      path: '/example',
      aria_label: '',
      lang: 'sl',
    },
    {
      label: 'suomi',
      path: '/example',
      aria_label: '',
      lang: 'fi',
    },
    {
      label: 'svenska',
      path: '/example',
      aria_label: '',
      lang: 'sv',
    },
  ],
  overlay: false,
  non_eu_items: [
    {
      label: '中文',
      path: '/example',
      aria_label: '',
      lang: 'zh',
    },
    {
      label: 'Türk',
      path: '/example',
      aria_label: '',
      lang: 'tr',
    },
    {
      label: 'pусский',
      path: '/example',
      aria_label: '',
      lang: 'ru',
    },
    {
      label: 'Català',
      path: '/example',
      aria_label: '',
      lang: 'ca',
    },
    {
      label: 'عَرَبِيّ',
      path: '/example',
      aria_label: '',
      lang: 'ar',
    },
  ],
  eu_category: 'EU official languages',
  non_eu_category: 'Non-EU languages',
  icon_path: 'static/media/icons.3cf410f9.svg',
  logo: {
    alt: 'European Commission logo',
    path: 'static/media/logo--mute.4f84735f.svg',
  },
};
