module.exports = {
  logo: {
    title: 'Home (European Commission)',
    alt: 'European Commission logo',
    href: '/example',
    language: 'en',
  },
  loginToggle: {
    labelNotLogged: 'Log in',
    hrefNotLogged: '/example',
    labelLogged: 'Logged in',
    hrefLogged: '/example',
  },
  loginBox: {
    id: 'login-box-id',
    description: 'Logged in as <last name>, <first name>',
    label: 'Log out',
    href: '/example',
  },
  languageSelector: {
    href: '/example',
    label: 'English',
    code: 'en',
    overlay: {
      closeLabel: 'Close',
      title: 'Select your language',
      categoryEu: 'EU official languages',
      items: [
        { lang: 'bg', label: 'български', href: '/example' },
        { lang: 'es', label: 'español', href: '/example' },
        { lang: 'cs', label: 'čeština', href: '/example' },
        { lang: 'da', label: 'dansk', href: '/example' },
        { lang: 'de', label: 'Deutsch', href: '/example' },
        { lang: 'et', label: 'eesti', href: '/example' },
        { lang: 'el', label: 'ελληνικά', href: '/example' },
        { lang: 'en', label: 'English', href: '/example', isActive: true },
        { lang: 'fr', label: 'français', href: '/example' },
        { lang: 'ga', label: 'Gaeilge', href: '/example' },
        { lang: 'hr', label: 'hrvatski', href: '/example' },
        { lang: 'it', label: 'italiano', href: '/example' },
        { lang: 'lv', label: 'latviešu', href: '/example' },
        { lang: 'lt', label: 'lietuvių', href: '/example' },
        { lang: 'hu', label: 'magyar', href: '/example' },
        { lang: 'mt', label: 'Malti', href: '/example' },
        { lang: 'nl', label: 'Nederlands', href: '/example' },
        { lang: 'pl', label: 'polski', href: '/example' },
        { lang: 'pt', label: 'português', href: '/example' },
        { lang: 'ro', label: 'română', href: '/example' },
        { lang: 'sk', label: 'slovenčina', href: '/example' },
        { lang: 'sl', label: 'slovenščina', href: '/example' },
        { lang: 'fi', label: 'suomi', href: '/example' },
        { lang: 'sv', label: 'svenska', href: '/example' },
      ],
      categoryNonEu: 'Non-EU languages',
      itemsNonEu: [
        { lang: 'zh', label: '中文', href: '/example' },
        { lang: 'tr', label: 'Türk', href: '/example' },
        { lang: 'ru', label: 'pусский', href: '/example' },
        { lang: 'ca', label: 'Català', href: '/example' },
        { lang: 'ar', label: 'عَرَبِيّ', href: '/example' },
      ],
    },
  },
  searchToggle: {
    label: 'Search',
    href: '/example',
  },
  searchForm: {
    id: 'search-form-id',
    textInputId: 'search-input-id',
    inputLabel: 'Search',
    buttonLabel: 'Search',
  },
};
