// Simple content for demo
module.exports = {
  logoAlt: 'European Union logo',
  items: [
    { id: '1', label: 'български', href: '/example#language_bg' },
    { id: '2', label: 'čeština', href: '/example#language_cs' },
    { id: '3', label: 'dansk', href: '/example#language_da' },
    { id: '4', label: 'Deutsch', href: '/example#language_de' },
    { id: '5', label: 'eesti', href: '/example#language_et' },
    { id: '6', label: 'ελληνικά', href: '/example#language_el' },
    { id: '7', label: 'English', href: '/example#language_en', isActive: true },
    { id: '8', label: 'español', href: '/example#language_es' },
    { id: '9', label: 'français', href: '/example#language_fr' },
    { id: '10', label: 'Gaeilge', href: '/example#language_ga' },
    { id: '11', label: 'hrvatski', href: '/example#language_hr' },
    { id: '12', label: 'italiano', href: '/example#language_it' },
    { id: '13', label: 'latviešu', href: '/example#language_lv' },
    { id: '14', label: 'lietuvių', href: '/example#language_lt' },
    { id: '15', label: 'magyar', href: '/example#language_hu' },
    { id: '16', label: 'Malti', href: '/example#language_mt' },
    { id: '17', label: 'Nederlands', href: '/example#language_nl' },
    { id: '18', label: 'polski', href: '/example#language_pl' },
    { id: '19', label: 'português', href: '/example#language_pt' },
    { id: '20', label: 'română', href: '/example#language_ro' },
    { id: '21', label: 'slovenčina', href: '/example#language_sk' },
    { id: '22', label: 'slovenščina', href: '/example#language_sl' },
    { id: '23', label: 'suomi', href: '/example#language_fi' },
    { id: '24', label: 'svenska', href: '/example#language_sv' },
  ],
};
