// Simple content for demo
module.exports = {
  group: 'group2',
  title: 'Menu',
  close: 'Close',
  back: 'Back',
  menu_link: '/example',
  icon_path: '/icons.svg',
  items: [
    { label: 'Home', path: '/example' },
    {
      label: 'Item 2 label',
      path: '/example',
      is_current: true,
      children: [
        { label: 'Item 2.1', path: '/example' },
        { label: 'Item 2.2', path: '/example' },
        { label: 'Item 2.3', path: '/example', is_current: true },
        { label: 'Item 2.4', path: '/example' },
        { label: 'Item 2.5', path: '/example' },
        { label: 'Item 2.6', path: '/example' },
        { label: 'Item 2.7', path: '/example' },
        { label: 'Item 2.8', path: '/example' },
        { label: 'Item 2.9', path: '/example' },
        { label: 'Item 2.10', path: '/example' },
        { label: 'Item 2.11', path: '/example' },
        { label: 'Item 2.12', path: '/example' },
        { label: 'Item 2.13', path: '/example' },
        { label: 'Item 2.14', path: '/example' },
        { label: 'Item 2.15', path: '/example' },
        { label: 'Item 2.16', path: '/example' },
      ],
    },
    {
      label: 'Item 3 label',
      path: '/example',
      children: [
        { label: 'Item 3.1', path: '/example' },
        { label: 'Item 3.2', path: '/example' },
        { label: 'Item 3.3', path: '/example' },
      ],
    },
    {
      label: 'Item 4 label',
      path: '/example',
      children: [
        { label: 'Item 4.1', path: '/example' },
        { label: 'Item 4.2', path: '/example' },
        {
          label: 'Item 4.3 with a very long label going on 2 lines',
          path: '/example',
        },
        { label: 'Item 4.4', path: '/example' },
        { label: 'Item 4.5', path: '/example' },
        { label: 'Item 4.6', path: '/example' },
        { label: 'Item 4.7', path: '/example' },
        { label: 'Item 4.8', path: '/example' },
        { label: 'Item 4.9', path: '/example' },
        { label: 'Item 4.10', path: '/example' },
        { label: 'Item 4.11', path: '/example' },
        { label: 'Item 4.12', path: '/example' },
        { label: 'Item 4.13', path: '/example' },
        { label: 'Item 4.14', path: '/example' },
      ],
    },
    {
      label: 'Item 5 label',
      path: '/example',
      children: [
        { label: 'Item 5.1', path: '/example' },
        { label: 'Item 5.2', path: '/example' },
        { label: 'Item 5.3', path: '/example' },
        { label: 'Item 5.4', path: '/example' },
        { label: 'Item 5.5', path: '/example' },
        { label: 'Item 5.6', path: '/example' },
        { label: 'Item 5.7', path: '/example' },
      ],
    },
    {
      label: 'Item 6 label',
      path: '/example',
      children: [
        { label: 'Item 6.1', path: '/example' },
        { label: 'Item 6.2', path: '/example' },
        { label: 'Item 6.3', path: '/example' },
        { label: 'Item 6.4', path: '/example' },
        { label: 'Item 6.5', path: '/example' },
        { label: 'Item 6.6', path: '/example' },
        { label: 'Item 6.7', path: '/example' },
        { label: 'Item 6.8', path: '/example' },
        { label: 'Item 6.9 with a very long label', path: '/example' },
        { label: 'Item 6.10', path: '/example' },
        { label: 'Item 6.11', path: '/example' },
        { label: 'Item 6.12', path: '/example' },
        { label: 'Item 6.13', path: '/example' },
        { label: 'Item 6.14', path: '/example' },
        { label: 'Item 6.15', path: '/example' },
        { label: 'Item 6.16', path: '/example' },
      ],
    },
    {
      label: 'Item 7 with a longer label',
      path: '/example',
      children: [
        { label: 'Item 7.1', path: '/example' },
        { label: 'Item 7.2', path: '/example' },
        { label: 'Item 7.3', path: '/example' },
        { label: 'Item 7.4', path: '/example' },
        { label: 'Item 7.5', path: '/example' },
        { label: 'Item 7.6', path: '/example' },
        { label: 'Item 7.7', path: '/example' },
        { label: 'Item 7.8', path: '/example' },
        { label: 'Item 7.9', path: '/example' },
        { label: 'Item 7.10', path: '/example' },
      ],
    },
  ],
};
