// Simple content for demo
module.exports = {
  label: 'Menu',
  items: [
    { label: 'Home', href: '/example#menu1' },
    {
      label: 'Policy',
      href: '/example#menu2',
      children: [
        { label: 'Item 2.1', href: '/example#menu2-1' },
        { label: 'Item 2.2', href: '/example#menu2-2' },
        { label: 'Item 2.3', href: '/example#menu2-3' },
        { label: 'Item 2.4', href: '/example#menu2-4' },
        { label: 'Item 2.5', href: '/example#menu2-5' },
        { label: 'Item 2.6', href: '/example#menu2-6' },
        { label: 'Item 2.7', href: '/example#menu2-7', isCurrent: true },
        { label: 'Item 2.8', href: '/example#menu2-8' },
        { label: 'Item 2.9', href: '/example#menu2-9' },
        { label: 'Item 2.10', href: '/example#menu2-10' },
      ],
    },
    {
      label: 'Advisor Bodies',
      href: '/example#menu3',
      children: [
        { label: 'Item 3.1', href: '/example#menu3-1' },
        { label: 'Item 3.2', href: '/example#menu3-2' },
        { label: 'Item 3.3', href: '/example#menu3-3' },
        { label: 'Item 3.4', href: '/example#menu3-4' },
        { label: 'Item 3.5', href: '/example#menu3-5' },
        { label: 'Item 3.6', href: '/example#menu3-6' },
        { label: 'Item 3.7', href: '/example#menu3-7' },
        { label: 'Item 3.8', href: '/example#menu3-8' },
        { label: 'Item 3.9', href: '/example#menu3-9' },
        { label: 'Item 3.10', href: '/example#menu3-10' },
      ],
    },
    {
      label: 'News & Events',
      href: '/example#menu4',
      children: [
        { label: 'Item 4.1', href: '/example#menu4-1' },
        { label: 'Item 4.2', href: '/example#menu4-2' },
        { label: 'Item 4.3', href: '/example#menu4-3' },
        { label: 'Item 4.4', href: '/example#menu4-4' },
        { label: 'Item 4.5', href: '/example#menu4-5' },
        { label: 'Item 4.6', href: '/example#menu4-6' },
        { label: 'Item 4.7', href: '/example#menu4-7' },
        { label: 'Item 4.8', href: '/example#menu4-8' },
        { label: 'Item 4.9', href: '/example#menu4-9' },
        { label: 'Item 4.10', href: '/example#menu4-10' },
      ],
    },
    {
      label: 'Contract and Fundings',
      href: '/example#menu5',
      children: [
        { label: 'Item 5.1', href: '/example#menu5-1' },
        { label: 'Item 5.2', href: '/example#menu5-2' },
        { label: 'Item 5.3', href: '/example#menu5-3' },
        { label: 'Item 5.4', href: '/example#menu5-4' },
        { label: 'Item 5.5', href: '/example#menu5-5' },
        { label: 'Item 5.6', href: '/example#menu5-6' },
        { label: 'Item 5.7', href: '/example#menu5-7' },
        { label: 'Item 5.8', href: '/example#menu5-8' },
        { label: 'Item 5.9', href: '/example#menu5-9' },
        { label: 'Item 5.10', href: '/example#menu5-10' },
      ],
    },
    {
      label: 'Documentation',
      href: '/example#menu6',
      children: [
        { label: 'Item 6.1', href: '/example#menu6-1' },
        { label: 'Item 6.2', href: '/example#menu6-2' },
        { label: 'Item 6.3', href: '/example#menu6-3' },
        { label: 'Item 6.4', href: '/example#menu6-4' },
        { label: 'Item 6.5', href: '/example#menu6-5' },
        { label: 'Item 6.6', href: '/example#menu6-6' },
        { label: 'Item 6.7', href: '/example#menu6-7' },
        { label: 'Item 6.8', href: '/example#menu6-8' },
        { label: 'Item 6.9', href: '/example#menu6-9' },
        { label: 'Item 6.10', href: '/example#menu6-10' },
      ],
    },
    { label: 'About Us', href: '/example#menu7' },
  ],
};
